var page = window.location.pathname;
var pokemonNum = 443;
var item;
var colour;
$(document).ready(function () {

  if (page == '/' || page == '/index.html' || page == '/index') {
    item = "checked-checkboxes";
    colour = "#62D17A";
  } else if (page == '/lucky.html' || page == '/lucky') {
    item = "lucky-checked-checkboxes";
    colour = "#FFDF7F";
  } else if (page == '/100.html'|| page == '/100') {
    item = "100-checked-checkboxes";
    colour = "#F5A65B";
  } else if (page == '/gender.html'|| page == '/gender') {
    item = "gender-checked-checkboxes";
    mcolour = "#66acd0";
    fcolour = "#F4A698";
  }

  if (localStorage.getItem('hideChecked') == null) {
    localStorage.setItem('hideChecked', "false");
  }

  if (localStorage.getItem(item) && $.parseJSON(localStorage.getItem(item)).length !== 0) {
    var arrCheckedCheckboxes = $.parseJSON(localStorage.getItem(item));
    $(arrCheckedCheckboxes.toString()).prop('checked', true);
    arrCheckedCheckboxes.forEach(function(obj) {
      var num = "cont";
      var n = obj.substr(1);
      num += n;
      changeColour(num);
      if (localStorage.getItem('hideChecked') == "false"){
        document.getElementById(num).parentElement.style.display = 'inline-grid';
      } else {
        $("#toggleChecked").html("Show");
        document.getElementById(num).parentElement.style.display = 'none';
      }
    })
    if (page == '/' || page == '/index.html' || page == '/index') {
      var checkedBoxes = document.querySelectorAll('input[name=dex]:checked');
      var width = Math.round(checkedBoxes.length / pokemonNum * 10000) / 100;
      document.getElementById("myBar").style.width = width + '%';
      document.getElementById("barLabel").innerHTML = "Pokedex Completion: " + width * 1  + '%' + " | " + checkedBoxes.length + " / " + pokemonNum;
    }

    $( ".section" ).each(function( index, obj ) {
      if($(obj).children(':visible').length < 2) {
        $(obj).children( ".sectionLabel" ).css( "display", "none" );
      }
    });
  }

  $("input:checkbox").change(function () {
    var arrCheckedCheckboxes = [];
    $.each($("input:checkbox:checked"), function () {
        arrCheckedCheckboxes.push("#" + $(this).attr('id'));
    });
    var num = "cont";
    num += $(this).attr('id');
    if (this.checked) {
      changeColour(num);
    }
    else {
      document.getElementById(num).style.backgroundColor = "#D3D3D3";
    }
    if (page == '/' || page == '/index.html' || page == '/index') {
      var checkedBoxes = document.querySelectorAll('input[name=dex]:checked');
      var width = Math.round(checkedBoxes.length / pokemonNum * 10000) / 100;
      document.getElementById("myBar").style.width = width + '%';
      document.getElementById("barLabel").innerHTML = "Pokedex Completion: " + width * 1  + '%' + " | " + checkedBoxes.length + " / " + pokemonNum;
    }
    localStorage.setItem(item, JSON.stringify(arrCheckedCheckboxes));
  });
});
$("#export").on("click", startExport);
$("#import").on("click", function() {
    startImport(prompt("Please paste your save:", ""));
 });
$("#toString").on("click", toString);
$("#toggleChecked").on("click", toggleChecked);
$(window).on("paste", function(e) {
  startImport(e.originalEvent.clipboardData.getData("text/plain"));
});

window.Clipboard = (function(window, document, navigator) {
  var textArea, copy;

  function isOS() {
    return navigator.userAgent.match(/ipad|iphone/i);
  }

  function createTextArea(text) {
    textArea = document.createElement('textArea');
    textArea.value = text;
    document.body.appendChild(textArea);
  }

  function selectText() {
    var range, selection;

    if (isOS()) {
      range = document.createRange();
      range.selectNodeContents(textArea);
      selection = window.getSelection();
      selection.removeAllRanges();
      selection.addRange(range);
      textArea.setSelectionRange(0, 999999);
    } else {
      textArea.select();
    }
  }

  function copyToClipboard() {
    document.execCommand('copy');
    document.body.removeChild(textArea);
  }

  copy = function(text) {
    createTextArea(text);
    selectText();
    copyToClipboard();
  };

  return {
    copy: copy
  };
})(window, document, navigator);

function confirmation() {
  if (confirm("Are you sure you want to reset?")) {
    localStorage.clear();
     window.location.href ="/"
     window.scrollTo(0,0);
  }
}

window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 100 || document.documentElement.scrollTop > 100) {
    document.getElementById("topBtn").style.display = "block";
  } else {
    document.getElementById("topBtn").style.display = "none";
  }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
  document.body.scrollTop = 0; // For Safari
  document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
}

function menu() {
  var x = document.getElementById("myLinks");
  if (x.style.display === "block") {
    x.style.display = "none";
    document.getElementById("line-break").style.display = "none";
  } else {
    x.style.display = "block";
    document.getElementById("line-break").style.display = "block";
  }
}

function toggleChecked(){
  var x = $("input:checkbox:checked").parent().parent();
  if(x.css("display") == "inline-grid") {
    x.css("display", "none");
    localStorage.setItem('hideChecked', true);
    hideLabels();
    $("#toggleChecked").html("Show");
  } else {
    x.css("display", "inline-grid");
    localStorage.setItem('hideChecked', false);
    showLabels();
    $("#toggleChecked").html("Hide");
  }
}

function hideLabels(){
  $( ".section" ).each(function( index, obj ) {
    if($(obj).children(':visible').length < 2) {
      $(obj).children( ".sectionLabel" ).css( "display", "none" );
    }
  });
}

function showLabels() {
  $( ".section" ).each(function( index, obj ) {
    $(obj).children( ".sectionLabel" ).css( "display", "block" );
  });
}

function startExport() {
  if ((localStorage.getItem(item) && $.parseJSON(localStorage.getItem(item)).length !== 0) ||
  (localStorage.getItem('lucky-checked-checkboxes') && $.parseJSON(localStorage.getItem('lucky-checked-checkboxes')).length !== 0 ) ||
  (localStorage.getItem('100-checked-checkboxes') && $.parseJSON(localStorage.getItem('100-checked-checkboxes')).length !== 0 ) ||
  (localStorage.getItem('gender-checked-checkboxes') && $.parseJSON(localStorage.getItem('gender-checked-checkboxes')).length !== 0 )){
    var encoded = btoa(JSON.stringify(localStorage));
    Clipboard.copy(encoded);
    alert("Copied to Clipboard!");
  } else {
    alert("Nothing to export!");
  }
}

function startImport(data) {
  try {
    Object.assign(localStorage,JSON.parse(atob(data)));
    if (localStorage.getItem(item) && $.parseJSON(localStorage.getItem(item)).length !== 0 ) {
      var checked = JSON.parse(localStorage.getItem(item));
      $(checked.toString()).prop('checked', true);
      checked.forEach(function(obj) {
        var num = "cont";
        var n = obj.substr(1);
        num += n;
        changeColour(num);
      })
    }
    alert("Import successful!");
    location.reload();
  } catch (Exception) {
    alert("Pasted invalid data!")
  }
}

function changeColour(num){
  if (page == '/gender.html'|| page == '/gender') {
    if (num.slice(-1) == "m") {
      document.getElementById(num).style.backgroundColor = mcolour;
    } else if (num.slice(-1) == "f") {
      document.getElementById(num).style.backgroundColor = fcolour;
    }
  } else {
    document.getElementById(num).style.backgroundColor = colour;
  }
}

var PokedexController = /** @class */ (function () {
  function PokedexController(pokedexService) {
    this.pokedexService = pokedexService;
  }
  PokedexController.prototype.print = function () {
    window.print();
  };
  return PokedexController;
}());

var PokedexService = /** @class */ (function () {
    function PokedexService() {
        this.shinies = [{ "id": "001", "name": "Bulbasaur" },
          { "id": "002", "name": "Ivysaur" },
          { "id": "003", "name": "Venusaur" },
          { "id": "004", "name": "Charmander" },
          { "id": "005", "name": "Charmeleon" },
          { "id": "006", "name": "Charizard" },
          { "id": "007", "name": "Squirtle" },
          { "id": "008", "name": "Wortortle" },
          { "id": "009", "name": "Blastoise" },
          { "id": "007-sunglasses", "name": "Summer Squirtle" },
          { "id": "008-sunglasses", "name": "Summer Wortortle" },
          { "id": "009-sunglasses", "name": "Summer Blastoise" },
          { "id": "010", "name": "Caterpie" },
          { "id": "011", "name": "Metapod" },
          { "id": "012", "name": "Butterfree" },
          { "id": "025", "name": "Pikachu" },
          { "id": "026", "name": "Raichu" },
          { "id": "025-party", "name": "Party Pikachu" },
          { "id": "026-party", "name": "Party Raichu" },
          { "id": "025-fragment", "name": "Fragment Pikachu" },
          { "id": "026-fragment", "name": "Fragment Raichu" },
          { "id": "025-halloween", "name": "Witch Pikachu" },
          { "id": "026-halloween", "name": "Witch Raichu" },
          { "id": "025-santa", "name": "Santa Pikachu" },
          { "id": "026-santa", "name": "Santa Raichu" },
          { "id": "026-a", "name": "Alolan Raichu" },
          { "id": "027", "name": "Sandshrew" },
          { "id": "028", "name": "Sandslash" },
          { "id": "029", "name": "Nidoran" },
          { "id": "030", "name": "Nidorina" },
          { "id": "031", "name": "Nidoqueen" },
          { "id": "058", "name": "Growlithe" },
          { "id": "059", "name": "Arcanine" },
          { "id": "074", "name": "Geodude" },
          { "id": "075", "name": "Graveler" },
          { "id": "076", "name": "Golem" },
          { "id": "077", "name": "Ponyta" },
          { "id": "078", "name": "Rapidash" },
          { "id": "081", "name": "Magnemite" },
          { "id": "082", "name": "Magneton" },
          { "id": "088", "name": "Grimer" },
          { "id": "089", "name": "Muk" },
          { "id": "090", "name": "Shellder" },
          { "id": "091", "name": "Cloister" },
          { "id": "092", "name": "Gastly" },
          { "id": "093", "name": "Haunter" },
          { "id": "094", "name": "Gengar" },
          { "id": "096", "name": "Drowzee" },
          { "id": "097", "name": "Hypno" },
          { "id": "098", "name": "Krabby" },
          { "id": "099", "name": "Kingler" },
          { "id": "104", "name": "Cubone" },
          { "id": "105", "name": "Marowak" },
          { "id": "105-a", "name": "Alolan Marowak" },
          { "id": "125", "name": "Electabuzz" },
          { "id": "126", "name": "Magmar" },
          { "id": "127", "name": "Pinsir" },
          { "id": "129", "name": "Magicarp", },
          { "id": "130", "name": "Gyarados" },
          { "id": "133", "name": "Eevee" },
          { "id": "134", "name": "Vaporeon" },
          { "id": "135", "name": "Jolteon" },
          { "id": "136", "name": "Flareon" },
          { "id": "138", "name": "Omanyte" },
          { "id": "139", "name": "Omantar" },
          { "id": "140", "name": "Kabuto" },
          { "id": "141", "name": "Kabutops" },
          { "id": "142", "name": "Aerodactyl" },
          { "id": "144", "name": "Articuno" },
          { "id": "145", "name": "Zapdos" },
          { "id": "146", "name": "Moltres" },
          { "id": "147", "name": "Dratini" },
          { "id": "148", "name": "Dragonair" },
          { "id": "149", "name": "Dragonite" },
          { "id": "152", "name": "Chikorita" },
          { "id": "153", "name": "Bayleef" },
          { "id": "154", "name": "Meganium" },
          { "id": "155", "name": "Cyndaquil" },
          { "id": "156", "name": "Quilava" },
          { "id": "157", "name": "Typhlosion" },
          { "id": "158", "name": "Totodile" },
          { "id": "159", "name": "Croconaw" },
          { "id": "160", "name": "Feraligatr" },
          { "id": "172", "name": "Pichu" },
          { "id": "172-party", "name": "Party Pichu" },
          { "id": "172-halloween", "name": "Witch Pichu" },
          { "id": "172-santa", "name": "Santa Pichu" },
          { "id": "175", "name": "Togepi" },
          { "id": "176", "name": "Togetic" },
          { "id": "177", "name": "Natu" },
          { "id": "178", "name": "Xatu" },
          { "id": "179", "name": "Mareep" },
          { "id": "180", "name": "Flaafy" },
          { "id": "181", "name": "Ampharos" },
          { "id": "183", "name": "Marill" },
          { "id": "184", "name": "Azumarill" },
          { "id": "191", "name": "Sunkern" },
          { "id": "192", "name": "Sunflora" },
          { "id": "196", "name": "Espeon" },
          { "id": "197", "name": "Umbreon" },
          { "id": "198", "name": "Murkrow" },
          { "id": "200", "name": "Misdreavus" },
          { "id": "202", "name": "Wobbuffet" },
          { "id": "204", "name": "Pineco" },
          { "id": "205", "name": "Forretress" },
          { "id": "209", "name": "Snubbull" },
          { "id": "210", "name": "Granbull" },
          { "id": "225", "name": "Delibird" },
          { "id": "228", "name": "Houndour" },
          { "id": "229", "name": "Houndoom" },
          { "id": "239", "name": "Elekid" },
          { "id": "240", "name": "Magby" },
          { "id": "246", "name": "Larvitar" },
          { "id": "247", "name": "Pupitar" },
          { "id": "248", "name": "Tyranitar" },
          { "id": "249", "name": "Lugia" },
          { "id": "250", "name": "Ho-oh" },
          { "id": "261", "name": "Poochyena" },
          { "id": "262", "name": "Mightyena" },
          { "id": "263", "name": "Zigzagoon" },
          { "id": "264", "name": "Linoone" },
          { "id": "276", "name": "Taillow" },
          { "id": "277", "name": "Swellow" },
          { "id": "278", "name": "Wingull" },
          { "id": "279", "name": "Pelipper" },
          { "id": "296", "name": "Makuhita" },
          { "id": "297", "name": "Hariyama" },
          { "id": "298", "name": "Azurill" },
          { "id": "302", "name": "Sableye" },
          { "id": "303", "name": "Mawile" },
          { "id": "304", "name": "Aron" },
          { "id": "305", "name": "Lairon" },
          { "id": "306", "name": "Aggron" },
          { "id": "307", "name": "Meditite" },
          { "id": "308", "name": "Medicham" },
          { "id": "311", "name": "Plusle" },
          { "id": "312", "name": "Minun" },
          { "id": "315", "name": "Roselia" },
          { "id": "320", "name": "Wailmer" },
          { "id": "321", "name": "Waillord" },
          { "id": "333", "name": "Swablu" },
          { "id": "334", "name": "Altaria" },
          { "id": "353", "name": "Shuppet" },
          { "id": "354", "name": "Banette" },
          { "id": "355", "name": "Duskull" },
          { "id": "356", "name": "Dusclops" },
          { "id": "359", "name": "Absol" },
          { "id": "360", "name": "Wynaut" },
          { "id": "361", "name": "Snorunt" },
          { "id": "362", "name": "Glaile" },
          { "id": "370", "name": "Luvdisk" },
          { "id": "374", "name": "Beldum" },
          { "id": "375", "name": "Metang" },
          { "id": "376", "name": "Metagross" },
          { "id": "382", "name": "Kyogre" },
          { "id": "403", "name": "Shinx" },
          { "id": "404", "name": "Luxio" },
          { "id": "405", "name": "Luxray" },
          { "id": "406", "name": "Budew" },
          { "id": "425", "name": "Drifloon" },
          { "id": "426", "name": "Drifblim" },
          { "id": "429", "name": "Mismagius" },
          { "id": "466", "name": "Electivire" },
          { "id": "407", "name": "Roserade" },
          { "id": "430", "name": "Honchkrow" },
          { "id": "467", "name": "Magmortar" },
          { "id": "468", "name": "Togekiss" },
          { "id": "477", "name": "Dusknoir" }];
        this.special = [{ "id": "172-santa", "name": "Santa Pichu" },
          { "id": "025-santa", "name": "Santa Pikachu" },
          { "id": "026-santa", "name": "Santa Raichu" },
          { "id": "172-party", "name": "Party Pichu" },
          { "id": "025-party", "name": "Party Pikachu" },
          { "id": "026-party", "name": "Party Raichu" },
          { "id": "172-ash", "name": "Ash Pichu" },
          { "id": "025-ash", "name": "Ash Pikachu" },
          { "id": "026-ash", "name": "Ash Raichu" },
          { "id": "172-halloween", "name": "Witch Pichu" },
          { "id": "025-halloween", "name": "Witch Pikachu" },
          { "id": "026-halloween", "name": "Witch Raichu" },
          { "id": "172-summer", "name": "Summer Pichu" },
          { "id": "025-summer", "name": "Summer Pikachu" },
          { "id": "026-summer", "name": "Summer Raichu" },
          { "id": "025-fragment", "name": "Fragment Pikachu" },
          { "id": "026-fragment", "name": "Fragment Raichu" },
          { "id": "007-sunglasses", "name": "Summer Squirtle" },
          { "id": "008-sunglasses", "name": "Summer Wartortle" },
          { "id": "009-sunglasses", "name": "Summer Blastoise" },
          { "id": "351-s", "name": "Sunny Castform" },
          { "id": "351-r", "name": "Rainy Castform" },
          { "id": "351-i", "name": "Snowy Castform" }];
        this.alolan = [{ "id": "019-a", "name": "Rattata" },
          { "id": "020-a", "name": "Raticate" },
          { "id": "026-a", "name": "Raichu" },
          { "id": "027-a", "name": "Sandshrew" },
          { "id": "028-a", "name": "Sandslash" },
          { "id": "037-a", "name": "Vulpix" },
          { "id": "038-a", "name": "Ninetales" },
          { "id": "050-a", "name": "Diglett" },
          { "id": "051-a", "name": "Dugtrio" },
          { "id": "052-a", "name": "Meowth" },
          { "id": "053-a", "name": "Persian" },
          { "id": "074-a", "name": "Geodude" },
          { "id": "075-a", "name": "Graveler" },
          { "id": "076-a", "name": "Golem" },
          { "id": "088-a", "name": "Grimer" },
          { "id": "089-a", "name": "Muk" },
          { "id": "103-a", "name": "Exeggutor" },
          { "id": "105-a", "name": "Marowak" }];
        this.spinda = [{ "id": "327", "name": "#1" },
          { "id": "327-3", "name": "#3" },
          { "id": "327-6", "name": "#6" },
          { "id": "327-7", "name": "#7" },
          { "id": "327-8", "name": "#8" }];
        this.unowns = [{ "id": "201-a", "name": "A" },
          { "id": "201-b", "name": "B" },
          { "id": "201-c", "name": "C" },
          { "id": "201-d", "name": "D" },
          { "id": "201-e", "name": "E" },
          { "id": "201-f", "name": "F" },
          { "id": "201-g", "name": "G" },
          { "id": "201-h", "name": "H" },
          { "id": "201-i", "name": "I" },
          { "id": "201-j", "name": "J" },
          { "id": "201-k", "name": "K" },
          { "id": "201-l", "name": "L" },
          { "id": "201-m", "name": "M" },
          { "id": "201-n", "name": "N" },
          { "id": "201-o", "name": "O" },
          { "id": "201-p", "name": "P" },
          { "id": "201-q", "name": "Q" },
          { "id": "201-r", "name": "R" },
          { "id": "201-s", "name": "S" },
          { "id": "201-t", "name": "T" },
          { "id": "201-u", "name": "U" },
          { "id": "201-v", "name": "V" },
          { "id": "201-w", "name": "W" },
          { "id": "201-x", "name": "X" },
          { "id": "201-y", "name": "Y" },
          { "id": "201-z", "name": "Z" },
          { "id": "201-!", "name": "!" },
          { "id": "201-qm", "name": "?" }];
        this.unavailable = [ { "id": "235", "name": "Smeargle" },
          { "id": "352", "name": "Kecleon" },
          { "id": "366", "name": "Clamperl" },
          { "id": "367", "name": "Huntail" },
          { "id": "368", "name": "Gorebyss" },
          { "id": "385", "name": "Jirachi" }];
        this.gen1 = [{ "id": "001", "name": "Bulbasaur" },
          { "id": "002", "name": "Ivysaur" },
          { "id": "003", "name": "Venusaur" },
          { "id": "004", "name": "Charmander" },
          { "id": "005", "name": "Charmeleon" },
          { "id": "006", "name": "Charizard" },
          { "id": "007", "name": "Squirtle" },
          { "id": "008", "name": "Wartortle" },
          { "id": "009", "name": "Blastoise" },
          { "id": "010", "name": "Caterpie" },
          { "id": "011", "name": "Metapod" },
          { "id": "012", "name": "Butterfree" },
          { "id": "013", "name": "Weedle" },
          { "id": "014", "name": "Kakuna" },
          { "id": "015", "name": "Beedrill" },
          { "id": "016", "name": "Pidgey" },
          { "id": "017", "name": "Pidgeotto" },
          { "id": "018", "name": "Pidgeot" },
          { "id": "019", "name": "Rattata" },
          { "id": "020", "name": "Raticate" },
          { "id": "021", "name": "Spearow" },
          { "id": "022", "name": "Fearow" },
          { "id": "023", "name": "Ekans" },
          { "id": "024", "name": "Arbok" },
          { "id": "025", "name": "Pikachu" },
          { "id": "026", "name": "Raichu" },
          { "id": "027", "name": "Sandshrew" },
          { "id": "028", "name": "Sandslash" },
          { "id": "029", "name": "Nidoran" },
          { "id": "030", "name": "Nidorina" },
          { "id": "031", "name": "Nidoqueen" },
          { "id": "032", "name": "Nidoran" },
          { "id": "033", "name": "Nidorino" },
          { "id": "034", "name": "Nidoking" },
          { "id": "035", "name": "Clefairy" },
          { "id": "036", "name": "Clefable" },
          { "id": "037", "name": "Vulpix" },
          { "id": "038", "name": "Ninetales" },
          { "id": "039", "name": "Jigglypuff" },
          { "id": "040", "name": "Wigglytuff" },
          { "id": "041", "name": "Zubat" },
          { "id": "042", "name": "Golbat" },
          { "id": "043", "name": "Oddish" },
          { "id": "044", "name": "Gloom" },
          { "id": "045", "name": "Vileplume" },
          { "id": "046", "name": "Paras" },
          { "id": "047", "name": "Parasect" },
          { "id": "048", "name": "Venonat" },
          { "id": "049", "name": "Venomoth" },
          { "id": "050", "name": "Diglett" },
          { "id": "051", "name": "Dugtrio" },
          { "id": "052", "name": "Meowth" },
          { "id": "053", "name": "Persian" },
          { "id": "054", "name": "Psyduck" },
          { "id": "055", "name": "Golduck" },
          { "id": "056", "name": "Mankey" },
          { "id": "057", "name": "Primeape" },
          { "id": "058", "name": "Growlithe" },
          { "id": "059", "name": "Arcanine" },
          { "id": "060", "name": "Poliwag" },
          { "id": "061", "name": "Poliwhirl" },
          { "id": "062", "name": "Poliwrath" },
          { "id": "063", "name": "Abra" },
          { "id": "064", "name": "Kadabra" },
          { "id": "065", "name": "Alakazam" },
          { "id": "066", "name": "Machop" },
          { "id": "067", "name": "Machoke" },
          { "id": "068", "name": "Machamp" },
          { "id": "069", "name": "Bellsprout" },
          { "id": "070", "name": "Weepinbell" },
          { "id": "071", "name": "Victreebel" },
          { "id": "072", "name": "Tentacool" },
          { "id": "073", "name": "Tentacruel" },
          { "id": "074", "name": "Geodude" },
          { "id": "075", "name": "Graveler" },
          { "id": "076", "name": "Golem" },
          { "id": "077", "name": "Ponyta" },
          { "id": "078", "name": "Rapidash" },
          { "id": "079", "name": "Slowpoke" },
          { "id": "080", "name": "Slowbro" },
          { "id": "081", "name": "Magnemite" },
          { "id": "082", "name": "Magneton" },
          { "id": "083", "name": "Farfetch'd" },
          { "id": "084", "name": "Doduo" },
          { "id": "085", "name": "Dodrio" },
          { "id": "086", "name": "Seel" },
          { "id": "087", "name": "Dewgong" },
          { "id": "088", "name": "Grimer" },
          { "id": "089", "name": "Muk" },
          { "id": "090", "name": "Shellder" },
          { "id": "091", "name": "Cloyster" },
          { "id": "092", "name": "Gastly" },
          { "id": "093", "name": "Haunter" },
          { "id": "094", "name": "Gengar" },
          { "id": "095", "name": "Onix" },
          { "id": "096", "name": "Drowzee" },
          { "id": "097", "name": "Hypno" },
          { "id": "098", "name": "Krabby" },
          { "id": "099", "name": "Kingler" },
          { "id": "100", "name": "Voltorb" },
          { "id": "101", "name": "Electrode" },
          { "id": "102", "name": "Exeggcute" },
          { "id": "103", "name": "Exeggutor" },
          { "id": "104", "name": "Cubone" },
          { "id": "105", "name": "Marowak" },
          { "id": "106", "name": "Hitmonlee" },
          { "id": "107", "name": "Hitmonchan" },
          { "id": "108", "name": "Lickitung" },
          { "id": "109", "name": "Koffing" },
          { "id": "110", "name": "Weezing" },
          { "id": "111", "name": "Rhyhorn" },
          { "id": "112", "name": "Rhydon" },
          { "id": "113", "name": "Chansey" },
          { "id": "114", "name": "Tangela" },
          { "id": "115", "name": "Kangaskhan" },
          { "id": "116", "name": "Horsea" },
          { "id": "117", "name": "Seadra" },
          { "id": "118", "name": "Goldeen" },
          { "id": "119", "name": "Seaking" },
          { "id": "120", "name": "Staryu" },
          { "id": "121", "name": "Starmie" },
          { "id": "122", "name": "Mr. Mime" },
          { "id": "123", "name": "Scyther" },
          { "id": "124", "name": "Jynx" },
          { "id": "125", "name": "Electabuzz" },
          { "id": "126", "name": "Magmar" },
          { "id": "127", "name": "Pinsir" },
          { "id": "128", "name": "Tauros" },
          { "id": "129", "name": "Magikarp" },
          { "id": "130", "name": "Gyarados" },
          { "id": "131", "name": "Lapras" },
          { "id": "132", "name": "Ditto" },
          { "id": "133", "name": "Eevee" },
          { "id": "134", "name": "Vaporeon" },
          { "id": "135", "name": "Jolteon" },
          { "id": "136", "name": "Flareon" },
          { "id": "137", "name": "Porygon" },
          { "id": "138", "name": "Omanyte" },
          { "id": "139", "name": "Omastar" },
          { "id": "140", "name": "Kabuto" },
          { "id": "141", "name": "Kabutops" },
          { "id": "142", "name": "Aerodactyl" },
          { "id": "143", "name": "Snorlax" },
          { "id": "144", "name": "Articuno" },
          { "id": "145", "name": "Zapdos" },
          { "id": "146", "name": "Moltres" },
          { "id": "147", "name": "Dratini" },
          { "id": "148", "name": "Dragonair" },
          { "id": "149", "name": "Dragonite" },
          { "id": "150", "name": "Mewtwo" },
          { "id": "151", "name": "Mew" }];
        this.gen2 = [{ "id": "152", "name": "Chikorita" },
          { "id": "153", "name": "Bayleef" },
          { "id": "154", "name": "Meganium" },
          { "id": "155", "name": "Cyndaquil" },
          { "id": "156", "name": "Quilava" },
          { "id": "157", "name": "Typhlosion" },
          { "id": "158", "name": "Totodile" },
          { "id": "159", "name": "Croconaw" },
          { "id": "160", "name": "Feraligatr" },
          { "id": "161", "name": "Sentret" },
          { "id": "162", "name": "Furret" },
          { "id": "163", "name": "Hoothoot" },
          { "id": "164", "name": "Noctowl" },
          { "id": "165", "name": "Ledyba" },
          { "id": "166", "name": "Ledian" },
          { "id": "167", "name": "Spinarak" },
          { "id": "168", "name": "Ariados" },
          { "id": "169", "name": "Crobat" },
          { "id": "170", "name": "Chinchou" },
          { "id": "171", "name": "Lanturn" },
          { "id": "172", "name": "Pichu" },
          { "id": "173", "name": "Cleffa" },
          { "id": "174", "name": "Igglybuff" },
          { "id": "175", "name": "Togepi" },
          { "id": "176", "name": "Togetic" },
          { "id": "177", "name": "Natu" },
          { "id": "178", "name": "Xatu" },
          { "id": "179", "name": "Mareep" },
          { "id": "180", "name": "Flaaffy" },
          { "id": "181", "name": "Ampharos" },
          { "id": "182", "name": "Bellossom" },
          { "id": "183", "name": "Marill" },
          { "id": "184", "name": "Azumarill" },
          { "id": "185", "name": "Sudowoodo" },
          { "id": "186", "name": "Politoed" },
          { "id": "187", "name": "Hoppip" },
          { "id": "188", "name": "Skiploom" },
          { "id": "189", "name": "Jumpluff" },
          { "id": "190", "name": "Aipom" },
          { "id": "191", "name": "Sunkern" },
          { "id": "192", "name": "Sunflora" },
          { "id": "193", "name": "Yanma" },
          { "id": "194", "name": "Wooper" },
          { "id": "195", "name": "Quagsire" },
          { "id": "196", "name": "Espeon" },
          { "id": "197", "name": "Umbreon" },
          { "id": "198", "name": "Murkrow" },
          { "id": "199", "name": "Slowking" },
          { "id": "200", "name": "Misdreavus" },
          { "id": "201", "name": "Unown" },
          { "id": "202", "name": "Wobbuffet" },
          { "id": "203", "name": "Girafarig" },
          { "id": "204", "name": "Pineco" },
          { "id": "205", "name": "Forretress" },
          { "id": "206", "name": "Dunsparce" },
          { "id": "207", "name": "Gligar" },
          { "id": "208", "name": "Steelix" },
          { "id": "209", "name": "Snubbull" },
          { "id": "210", "name": "Granbull" },
          { "id": "211", "name": "Qwilfish" },
          { "id": "212", "name": "Scizor" },
          { "id": "213", "name": "Shuckle" },
          { "id": "214", "name": "Heracross" },
          { "id": "215", "name": "Sneasel" },
          { "id": "216", "name": "Teddiursa" },
          { "id": "217", "name": "Ursaring" },
          { "id": "218", "name": "Slugma" },
          { "id": "219", "name": "Magcargo" },
          { "id": "220", "name": "Swinub" },
          { "id": "221", "name": "Piloswine" },
          { "id": "222", "name": "Corsola" },
          { "id": "223", "name": "Remoraid" },
          { "id": "224", "name": "Octillery" },
          { "id": "225", "name": "Delibird" },
          { "id": "226", "name": "Mantine" },
          { "id": "227", "name": "Skarmory" },
          { "id": "228", "name": "Houndour" },
          { "id": "229", "name": "Houndoom" },
          { "id": "230", "name": "Kingdra" },
          { "id": "231", "name": "Phanpy" },
          { "id": "232", "name": "Donphan" },
          { "id": "233", "name": "Porygon2" },
          { "id": "234", "name": "Stantler" },
          { "id": "236", "name": "Tyrogue" },
          { "id": "237", "name": "Hitmontop" },
          { "id": "238", "name": "Smoochum" },
          { "id": "239", "name": "Elekid" },
          { "id": "240", "name": "Magby" },
          { "id": "241", "name": "Miltank" },
          { "id": "242", "name": "Blissey" },
          { "id": "243", "name": "Raikou" },
          { "id": "244", "name": "Entei" },
          { "id": "245", "name": "Suicune" },
          { "id": "246", "name": "Larvitar" },
          { "id": "247", "name": "Pupitar" },
          { "id": "248", "name": "Tyranitar" },
          { "id": "249", "name": "Lugia" },
          { "id": "250", "name": "Ho-Oh" },
          { "id": "251", "name": "Celebi" }];
        this.gen3 = [{ "id": "252", "name": "Treecko" },
          { "id": "253", "name": "Grovyle" },
          { "id": "254", "name": "Sceptile" },
          { "id": "255", "name": "Torchic" },
          { "id": "256", "name": "Combusken" },
          { "id": "257", "name": "Blaziken" },
          { "id": "258", "name": "Mudkip" },
          { "id": "259", "name": "Marshtomp" },
          { "id": "260", "name": "Swampert" },
          { "id": "261", "name": "Poochyena" },
          { "id": "262", "name": "Mightyena" },
          { "id": "263", "name": "Zigzagoon" },
          { "id": "264", "name": "Linoone" },
          { "id": "265", "name": "Wurmple" },
          { "id": "266", "name": "Silcoon" },
          { "id": "267", "name": "Beautifly" },
          { "id": "268", "name": "Cascoon" },
          { "id": "269", "name": "Dustox" },
          { "id": "270", "name": "Lotad" },
          { "id": "271", "name": "Lombre" },
          { "id": "272", "name": "Ludicolo" },
          { "id": "273", "name": "Seedot" },
          { "id": "274", "name": "Nuzleaf" },
          { "id": "275", "name": "Shiftry" },
          { "id": "276", "name": "Taillow" },
          { "id": "277", "name": "Swellow" },
          { "id": "278", "name": "Wingull" },
          { "id": "279", "name": "Pelipper" },
          { "id": "280", "name": "Ralts" },
          { "id": "281", "name": "Kirlia" },
          { "id": "282", "name": "Gardevoir" },
          { "id": "283", "name": "Surskit" },
          { "id": "284", "name": "Masquerain" },
          { "id": "285", "name": "Shroomish" },
          { "id": "286", "name": "Breloom" },
          { "id": "287", "name": "Slakoth" },
          { "id": "288", "name": "Vigoroth" },
          { "id": "289", "name": "Slaking" },
          { "id": "290", "name": "Nincada" },
          { "id": "291", "name": "Ninjask" },
          { "id": "292", "name": "Shedinja" },
          { "id": "293", "name": "Whismur" },
          { "id": "294", "name": "Loudred" },
          { "id": "295", "name": "Exploud" },
          { "id": "296", "name": "Makuhita" },
          { "id": "297", "name": "Hariyama" },
          { "id": "298", "name": "Azurill" },
          { "id": "299", "name": "Nosepass" },
          { "id": "300", "name": "Skitty" },
          { "id": "301", "name": "Delcatty" },
          { "id": "302", "name": "Sableye" },
          { "id": "303", "name": "Mawile" },
          { "id": "304", "name": "Aron" },
          { "id": "305", "name": "Lairon" },
          { "id": "306", "name": "Aggron" },
          { "id": "307", "name": "Meditite" },
          { "id": "308", "name": "Medicham" },
          { "id": "309", "name": "Electrike" },
          { "id": "310", "name": "Manectric" },
          { "id": "311", "name": "Plusle" },
          { "id": "312", "name": "Minun" },
          { "id": "313", "name": "Volbeat" },
          { "id": "314", "name": "Illumise" },
          { "id": "315", "name": "Roselia" },
          { "id": "316", "name": "Gulpin" },
          { "id": "317", "name": "Swalot" },
          { "id": "318", "name": "Carvanha" },
          { "id": "319", "name": "Sharpedo" },
          { "id": "320", "name": "Wailmer" },
          { "id": "321", "name": "Wailord" },
          { "id": "322", "name": "Numel" },
          { "id": "323", "name": "Camerupt" },
          { "id": "324", "name": "Torkoal" },
          { "id": "325", "name": "Spoink" },
          { "id": "326", "name": "Grumpig" },
          { "id": "327", "name": "Spinda" },
          { "id": "328", "name": "Trapinch" },
          { "id": "329", "name": "Vibrava" },
          { "id": "330", "name": "Flygon" },
          { "id": "331", "name": "Cacnea" },
          { "id": "332", "name": "Cacturne" },
          { "id": "333", "name": "Swablu" },
          { "id": "334", "name": "Altaria" },
          { "id": "335", "name": "Zangoose" },
          { "id": "336", "name": "Seviper" },
          { "id": "337", "name": "Lunatone" },
          { "id": "338", "name": "Solrock" },
          { "id": "339", "name": "Barboach" },
          { "id": "340", "name": "Whiscash" },
          { "id": "341", "name": "Corphish" },
          { "id": "342", "name": "Crawdaunt" },
          { "id": "343", "name": "Baltoy" },
          { "id": "344", "name": "Claydol" },
          { "id": "345", "name": "Lileep" },
          { "id": "346", "name": "Cradily" },
          { "id": "347", "name": "Anorith" },
          { "id": "348", "name": "Armaldo" },
          { "id": "349", "name": "Feebas" },
          { "id": "350", "name": "Milotic" },
          { "id": "351", "name": "Castform" },
          { "id": "353", "name": "Shuppet" },
          { "id": "354", "name": "Banette" },
          { "id": "355", "name": "Duskull" },
          { "id": "356", "name": "Dusclops" },
          { "id": "357", "name": "Tropius" },
          { "id": "358", "name": "Chimecho" },
          { "id": "359", "name": "Absol" },
          { "id": "360", "name": "Wynaut" },
          { "id": "361", "name": "Snorunt" },
          { "id": "362", "name": "Glalie" },
          { "id": "363", "name": "Spheal" },
          { "id": "364", "name": "Sealeo" },
          { "id": "365", "name": "Walrein" },
          { "id": "369", "name": "Relicanth" },
          { "id": "370", "name": "Luvdisc" },
          { "id": "371", "name": "Bagon" },
          { "id": "372", "name": "Shelgon" },
          { "id": "373", "name": "Salamence" },
          { "id": "374", "name": "Beldum" },
          { "id": "375", "name": "Metang" },
          { "id": "376", "name": "Metagross" },
          { "id": "377", "name": "Regirock" },
          { "id": "378", "name": "Regice" },
          { "id": "379", "name": "Registeel" },
          { "id": "380", "name": "Latias" },
          { "id": "381", "name": "Latios" },
          { "id": "382", "name": "Kyogre" },
          { "id": "383", "name": "Groudon" },
          { "id": "384", "name": "Rayquaza" },
          { "id": "386", "name": "Deoxys" }];
        this.gen4 = [{ "id": "387", "name": "Turtwig" },
          { "id": "388", "name": "Grotle" },
          { "id": "389", "name": "Torterra" },
          { "id": "390", "name": "Chimchar" },
          { "id": "391", "name": "Monferno" },
          { "id": "392", "name": "Infernape" },
          { "id": "393", "name": "Piplup" },
          { "id": "394", "name": "Prinplup" },
          { "id": "395", "name": "Empoleon" },
          { "id": "396", "name": "Starly" },
          { "id": "397", "name": "Staravia" },
          { "id": "398", "name": "Staraptor" },
          { "id": "399", "name": "Bidoof" },
          { "id": "400", "name": "Bibarel" },
          { "id": "401", "name": "Kricketot" },
          { "id": "402", "name": "Kricketune" },
          { "id": "403", "name": "Shinx" },
          { "id": "404", "name": "Luxio" },
          { "id": "405", "name": "Luxray" },
          { "id": "406", "name": "Budew" },
          { "id": "407", "name": "Roserade" },
          { "id": "417", "name": "Pachirisu" },
          { "id": "418", "name": "Buizel" },
          { "id": "419", "name": "Floatzel" },
          { "id": "425", "name": "Drifloon" },
          { "id": "426", "name": "Drifblim" },
          { "id": "427", "name": "Buneary" },
          { "id": "428", "name": "Lopunny" },
          { "id": "429", "name": "Mismagius" },
          { "id": "430", "name": "Honchkrow" },
          { "id": "433", "name": "Chingling" },
          { "id": "434", "name": "Stunky" },
          { "id": "435", "name": "Skuntank" },
          { "id": "436", "name": "Bronzor" },
          { "id": "437", "name": "Bronzong" },
          { "id": "441", "name": "Chatot" },
          { "id": "442", "name": "Spiritomb" },
          { "id": "446", "name": "Munchlax" },
          { "id": "447", "name": "Riolu" },
          { "id": "448", "name": "Lucario" },
          { "id": "451", "name": "Skorupi" },
          { "id": "452", "name": "Drapion" },
          { "id": "453", "name": "Croagunk" },
          { "id": "454", "name": "Toxicroak" },
          { "id": "455", "name": "Carnivine" },
          { "id": "456", "name": "Finneon" },
          { "id": "457", "name": "Lumineon" },
          { "id": "458", "name": "Mantyke" },
          { "id": "459", "name": "Snover" },
          { "id": "460", "name": "Abomasnow" },
          { "id": "461", "name": "Weavile" },
          { "id": "464", "name": "Rhyperior" },
          { "id": "466", "name": "Electivire" },
          { "id": "467", "name": "Magmortar" },
          { "id": "468", "name": "Togekiss" },
          { "id": "472", "name": "Gliscor" },
          { "id": "474", "name": "Porygon-Z" },
          { "id": "477", "name": "Dusknoir" },
          { "id": "485", "name": "Heatran" },
          { "id": "487", "name": "Giratina" },
          { "id": "488", "name": "Cresselia" }];
        this.mystery = [{ "id": "808", "name": "Meltan" },
          { "id": "809", "name": "Melmetal" }];
        this.genderShinies = [{ "id": "001-m", "name": "Bulbasaur ♂" },
          { "id": "001-f", "name": "Bulbasaur ♀" },
          { "id": "002-m", "name": "Ivysaur ♂" },
          { "id": "002-f", "name": "Ivysaur ♀" },
          { "id": "003-m", "name": "Venusaur ♂" },
          { "id": "003-f", "name": "Venusaur ♀" },
          { "id": "004-m", "name": "Charmander ♂" },
          { "id": "004-f", "name": "Charmander ♀" },
          { "id": "005-m", "name": "Charmeleon ♂" },
          { "id": "005-f", "name": "Charmeleon ♀" },
          { "id": "006-m", "name": "Charizard ♂" },
          { "id": "006-f", "name": "Charizard ♀" },
          { "id": "007-m", "name": "Squirtle ♂" },
          { "id": "007-f", "name": "Squirtle ♀" },
          { "id": "008-m", "name": "Wortortle ♂" },
          { "id": "008-f", "name": "Wortortle ♀" },
          { "id": "009-m", "name": "Blastoise ♂" },
          { "id": "009-f", "name": "Blastoise ♀" },
          { "id": "007-sunglasses-m", "name": "Summer Squirtle ♂" },
          { "id": "008-sunglasses-m", "name": "Summer Wortortle ♂" },
          { "id": "009-sunglasses-m", "name": "Summer Blastoise ♂" },
          { "id": "010-m", "name": "Caterpie ♂" },
          { "id": "010-f", "name": "Caterpie ♀" },
          { "id": "011-m", "name": "Metapod ♂" },
          { "id": "011-f", "name": "Metapod ♀" },
          { "id": "012-m", "name": "Butterfree ♂" },
          { "id": "012-f", "name": "Butterfree ♀" },
          { "id": "025-m", "name": "Pikachu ♂" },
          { "id": "025-f", "name": "Pikachu ♀" },
          { "id": "026-m", "name": "Raichu ♂" },
          { "id": "026-f", "name": "Raichu ♀" },
          { "id": "025-party-m", "name": "Party Pikachu ♂" },
          { "id": "025-party-f", "name": "Party Pikachu ♀" },
          { "id": "026-party-m", "name": "Party Raichu ♂" },
          { "id": "026-party-f", "name": "Party Raichu ♀" },
          { "id": "025-fragment-m", "name": "Fragment Pikachu ♂" },
          { "id": "025-fragment-f", "name": "Fragment Pikachu ♀" },
          { "id": "026-fragment-m", "name": "Fragment Raichu ♂" },
          { "id": "026-fragment-f", "name": "Fragment Raichu ♀" },
          { "id": "025-halloween-m", "name": "Witch Pikachu ♂" },
          { "id": "025-halloween-f", "name": "Witch Pikachu ♀" },
          { "id": "026-halloween-m", "name": "Witch Raichu ♂" },
          { "id": "026-halloween-f", "name": "Witch Raichu ♀" },
          { "id": "029-f", "name": "Nidoran ♀" },
          { "id": "030-f", "name": "Nidorina ♀" },
          { "id": "031-f", "name": "Nidoqueen ♀" },
          { "id": "058-m", "name": "Growlithe ♂" },
          { "id": "058-f", "name": "Growlithe" },
          { "id": "059-m", "name": "Arcanine ♂" },
          { "id": "059-f", "name": "Arcanine" },
          { "id": "074-m", "name": "Geodude ♂" },
          { "id": "074-f", "name": "Geodude" },
          { "id": "075-m", "name": "Graveler ♂" },
          { "id": "075-f", "name": "Graveler" },
          { "id": "076-m", "name": "Golem ♂" },
          { "id": "076-f", "name": "Golem" },
          { "id": "077-m", "name": "Ponyta ♂" },
          { "id": "077-f", "name": "Ponyta" },
          { "id": "078-m", "name": "Rapidash ♂" },
          { "id": "078-f", "name": "Rapidash" },
          { "id": "088-m", "name": "Grimer ♂" },
          { "id": "088-f", "name": "Grimer" },
          { "id": "089-m", "name": "Muk ♂" },
          { "id": "089-f", "name": "Muk" },
          { "id": "090-m", "name": "Shellder ♂" },
          { "id": "090-f", "name": "Shellder" },
          { "id": "091-m", "name": "Cloister ♂" },
          { "id": "091-f", "name": "Cloister" },
          { "id": "092-m", "name": "Gastly ♂" },
          { "id": "092-f", "name": "Gastly" },
          { "id": "093-m", "name": "Haunter ♂" },
          { "id": "093-f", "name": "Haunter" },
          { "id": "094-m", "name": "Gengar ♂" },
          { "id": "094-f", "name": "Gengar" },
          { "id": "096-m", "name": "Drowzee ♂" },
          { "id": "096-f", "name": "Drowzee" },
          { "id": "097-m", "name": "Hypno ♂" },
          { "id": "097-f", "name": "Hypno" },
          { "id": "098-m", "name": "Krabby ♂" },
          { "id": "098-f", "name": "Krabby" },
          { "id": "099-m", "name": "Kingler ♂" },
          { "id": "099-f", "name": "Kingler" },
          { "id": "104-m", "name": "Cubone ♂" },
          { "id": "104-f", "name": "Cubone" },
          { "id": "105-m", "name": "Marowak ♂" },
          { "id": "105-f", "name": "Marowak" },
          { "id": "126-m", "name": "Magmar ♂" },
          { "id": "126-f", "name": "Magmar" },
          { "id": "127-m", "name": "Pinsir ♂" },
          { "id": "127-f", "name": "Pinsir" },
          { "id": "129-m", "name": "Magicarp ♂", },
          { "id": "129-f", "name": "Magicarp", },
          { "id": "130-m", "name": "Gyarados ♂" },
          { "id": "130-f", "name": "Gyarados" },
          { "id": "133-m", "name": "Eevee ♂" },
          { "id": "133-f", "name": "Eevee" },
          { "id": "134-m", "name": "Vaporeon ♂" },
          { "id": "134-f", "name": "Vaporeon" },
          { "id": "135-m", "name": "Jolteon ♂" },
          { "id": "135-f", "name": "Jolteon" },
          { "id": "136-m", "name": "Flareon ♂" },
          { "id": "136-f", "name": "Flareon" },
          { "id": "138-m", "name": "Omanyte ♂" },
          { "id": "138-f", "name": "Omanyte" },
          { "id": "139-m", "name": "Omantar ♂" },
          { "id": "139-f", "name": "Omantar" },
          { "id": "140-m", "name": "Kabuto ♂" },
          { "id": "140-f", "name": "Kabuto" },
          { "id": "141-m", "name": "Kabutops ♂" },
          { "id": "141-f", "name": "Kabutops" },
          { "id": "142-m", "name": "Aerodactyl ♂" },
          { "id": "142-f", "name": "Aerodactyl" },
          { "id": "147-m", "name": "Dratini ♂" },
          { "id": "147-f", "name": "Dratini" },
          { "id": "148-m", "name": "Dragonair ♂" },
          { "id": "148-f", "name": "Dragonair" },
          { "id": "149-m", "name": "Dragonite ♂" },
          { "id": "149-f", "name": "Dragonite" },
          { "id": "152-m", "name": "Chikorita ♂" },
          { "id": "152-f", "name": "Chikorita" },
          { "id": "153-m", "name": "Bayleef ♂" },
          { "id": "153-f", "name": "Bayleef" },
          { "id": "154-m", "name": "Meganium ♂" },
          { "id": "154-f", "name": "Meganium" },
          { "id": "172-m", "name": "Pichu ♂" },
          { "id": "172-f", "name": "Pichu" },
          { "id": "172-party-m", "name": "Party Pichu ♂" },
          { "id": "172-party-f", "name": "Party Pichu" },
          { "id": "172-halloween-m", "name": "Witch Pichu ♂" },
          { "id": "172-halloween-f", "name": "Witch Pichu" },
          { "id": "175-m", "name": "Togepi ♂" },
          { "id": "175-f", "name": "Togepi" },
          { "id": "176-m", "name": "Togetic ♂" },
          { "id": "176-f", "name": "Togetic" },
          { "id": "177-m", "name": "Natu ♂" },
          { "id": "177-f", "name": "Natu" },
          { "id": "178-m", "name": "Xatu ♂" },
          { "id": "178-f", "name": "Xatu" },
          { "id": "179-m", "name": "Mareep ♂" },
          { "id": "179-f", "name": "Mareep" },
          { "id": "180-m", "name": "Flaafy ♂" },
          { "id": "180-f", "name": "Flaafy" },
          { "id": "181-m", "name": "Ampharos ♂" },
          { "id": "181-f", "name": "Ampharos" },
          { "id": "191-m", "name": "Sunkern ♂" },
          { "id": "191-f", "name": "Sunkern" },
          { "id": "192-m", "name": "Sunflora ♂" },
          { "id": "192-f", "name": "Sunflora" },
          { "id": "196-m", "name": "Espeon ♂" },
          { "id": "196-f", "name": "Espeon" },
          { "id": "197-m", "name": "Umbreon ♂" },
          { "id": "197-f", "name": "Umbreon" },
          { "id": "198-m", "name": "Murkrow ♂" },
          { "id": "198-f", "name": "Murkrow" },
          { "id": "202-m", "name": "Wobbuffet ♂" },
          { "id": "202-f", "name": "Wobbuffet" },
          { "id": "204-m", "name": "Pineco ♂" },
          { "id": "204-f", "name": "Pineco" },
          { "id": "205-m", "name": "Forretress ♂" },
          { "id": "205-f", "name": "Forretress" },
          { "id": "209-m", "name": "Snubbull ♂" },
          { "id": "209-f", "name": "Snubbull" },
          { "id": "210-m", "name": "Granbull ♂" },
          { "id": "210-f", "name": "Granbull" },
          { "id": "228-m", "name": "Houndour ♂" },
          { "id": "228-f", "name": "Houndour" },
          { "id": "229-m", "name": "Houndoom ♂" },
          { "id": "229-f", "name": "Houndoom" },
          { "id": "240-m", "name": "Magby ♂" },
          { "id": "240-f", "name": "Magby" },
          { "id": "246-m", "name": "Larvitar ♂" },
          { "id": "246-f", "name": "Larvitar" },
          { "id": "247-m", "name": "Pupitar ♂" },
          { "id": "247-f", "name": "Pupitar" },
          { "id": "248-m", "name": "Tyranitar ♂" },
          { "id": "248-f", "name": "Tyranitar" },
          { "id": "261-m", "name": "Poochyena ♂" },
          { "id": "261-f", "name": "Poochyena" },
          { "id": "262-m", "name": "Mighyena ♂" },
          { "id": "262-f", "name": "Mighyena" },
          { "id": "278-m", "name": "Wingull ♂" },
          { "id": "278-f", "name": "Wingull" },
          { "id": "279-m", "name": "Pelipper ♂" },
          { "id": "279-f", "name": "Pelipper" },
          { "id": "296-m", "name": "Makuhita ♂" },
          { "id": "296-f", "name": "Makuhita" },
          { "id": "297-m", "name": "Hariyama ♂" },
          { "id": "297-f", "name": "Hariyama" },
          { "id": "302-m", "name": "Sableye ♂" },
          { "id": "302-f", "name": "Sableye" },
          { "id": "303-m", "name": "Mawile ♂" },
          { "id": "303-f", "name": "Mawile" },
          { "id": "304-m", "name": "Aron ♂" },
          { "id": "304-f", "name": "Aron" },
          { "id": "305-m", "name": "Lairon ♂" },
          { "id": "305-f", "name": "Lairon" },
          { "id": "306-m", "name": "Aggron ♂" },
          { "id": "306-f", "name": "Aggron" },
          { "id": "307-m", "name": "Meditite ♂" },
          { "id": "307-f", "name": "Meditite" },
          { "id": "308-m", "name": "Medicham ♂" },
          { "id": "308-f", "name": "Medicham" },
          { "id": "311-m", "name": "Plusle ♂" },
          { "id": "311-f", "name": "Plusle" },
          { "id": "312-m", "name": "Minun ♂" },
          { "id": "312-f", "name": "Minun" },
          { "id": "315-m", "name": "Roselia ♂" },
          { "id": "315-f", "name": "Roselia" },
          { "id": "320-m", "name": "Wailmer ♂" },
          { "id": "320-f", "name": "Wailmer" },
          { "id": "321-m", "name": "Waillord ♂" },
          { "id": "321-f", "name": "Waillord" },
          { "id": "333-m", "name": "Swablu ♂" },
          { "id": "333-f", "name": "Swablu" },
          { "id": "334-m", "name": "Altaria ♂" },
          { "id": "334-f", "name": "Altaria" },
          { "id": "353-m", "name": "Shuppet ♂" },
          { "id": "353-f", "name": "Shuppet" },
          { "id": "354-m", "name": "Banette ♂" },
          { "id": "354-f", "name": "Banette" },
          { "id": "355-m", "name": "Duskull ♂" },
          { "id": "355-f", "name": "Duskull" },
          { "id": "356-m", "name": "Dusclops ♂" },
          { "id": "356-f", "name": "Dusclops" },
          { "id": "359-m", "name": "Absol ♂" },
          { "id": "359-f", "name": "Absol" },
          { "id": "360-m", "name": "Wynaut ♂" },
          { "id": "360-f", "name": "Wynaut" },
          { "id": "361-m", "name": "Snorunt ♂" },
          { "id": "361-f", "name": "Snorunt" },
          { "id": "362-m", "name": "Glaile ♂" },
          { "id": "362-f", "name": "Glaile" },
          { "id": "370-m", "name": "Luvdisk ♂" },
          { "id": "370-f", "name": "Luvdisk" }];
          //{ "id": "403", "name": "Shinx" },
          //{ "id": "404", "name": "Luxio" },
          //{ "id": "405", "name": "Luxray" },
          //{ "id": "406", "name": "Budew" },
          //{ "id": "425", "name": "Drifloon" },
          //{ "id": "426", "name": "Drifblim" }];
        this.genderSpecial = [{ "id": "172-santa-m", "name": "Santa Pichu ♂" },
          { "id": "172-santa-f", "name": "Santa Pichu ♀" },
          { "id": "025-santa-m", "name": "Santa Pikachu ♂" },
          { "id": "025-santa-f", "name": "Santa Pikachu ♀" },
          { "id": "026-santa-m", "name": "Santa Raichu ♂" },
          { "id": "026-santa-f", "name": "Santa Raichu ♀" },
          { "id": "172-party-m", "name": "Party Pichu ♂" },
          { "id": "172-party-f", "name": "Party Pichu ♀" },
          { "id": "025-party-m", "name": "Party Pikachu ♂" },
          { "id": "025-party-f", "name": "Party Pikachu ♀" },
          { "id": "026-party-m", "name": "Party Raichu ♂" },
          { "id": "026-party-f", "name": "Party Raichu ♀" },
          { "id": "172-ash-m", "name": "Ash Pichu ♂" },
          { "id": "172-ash-f", "name": "Ash Pichu ♀" },
          { "id": "025-ash-m", "name": "Ash Pikachu ♂" },
          { "id": "025-ash-f", "name": "Ash Pikachu ♀" },
          { "id": "026-ash-m", "name": "Ash Raichu ♂" },
          { "id": "026-ash-f", "name": "Ash Raichu ♀" },
          { "id": "172-halloween-m", "name": "Witch Pichu ♂" },
          { "id": "172-halloween-f", "name": "Witch Pichu ♀" },
          { "id": "025-halloween-m", "name": "Witch Pikachu ♂" },
          { "id": "025-halloween-f", "name": "Witch Pikachu ♀" },
          { "id": "026-halloween-m", "name": "Witch Raichu ♂" },
          { "id": "026-halloween-f", "name": "Witch Raichu ♀" },
          { "id": "172-summer-m", "name": "Summer Pichu ♂" },
          { "id": "172-summer-f", "name": "Summer Pichu ♀" },
          { "id": "025-summer-m", "name": "Summer Pikachu ♂" },
          { "id": "025-summer-f", "name": "Summer Pikachu ♀" },
          { "id": "026-summer-m", "name": "Summer Raichu ♂" },
          { "id": "026-summer-f", "name": "Summer Raichu ♀" },
          { "id": "025-fragment-m", "name": "Fragment Pikachu ♂" },
          { "id": "025-fragment-f", "name": "Fragment Pikachu ♀" },
          { "id": "026-fragment-m", "name": "Fragment Raichu ♂" },
          { "id": "026-fragment-f", "name": "Fragment Raichu ♀" },
          { "id": "007-sunglasses-m", "name": "Summer Squirtle ♂" },
          { "id": "008-sunglasses-m", "name": "Summer Wartortle ♂" },
          { "id": "009-sunglasses-m", "name": "Summer Blastoise ♂" },
          { "id": "351-s-m", "name": "Sunny Castform ♂" },
          { "id": "351-s-f", "name": "Sunny Castform ♀" },
          { "id": "351-r-m", "name": "Rainy Castform ♂" },
          { "id": "351-r-f", "name": "Rainy Castform ♀" },
          { "id": "351-i-m", "name": "Snowy Castform ♂" },
          { "id": "351-i-f", "name": "Snowy Castform ♀" }];
        this.genderAlolan = [{ "id": "019-a-m", "name": "Rattata ♂" },
          { "id": "019-a-f", "name": "Rattata ♀" },
          { "id": "020-a-m", "name": "Raticate ♂" },
          { "id": "020-a-f", "name": "Raticate ♀" },
          { "id": "026-a-m", "name": "Raichu ♂" },
          { "id": "026-a-f", "name": "Raichu ♀" },
          { "id": "027-a-m", "name": "Sandshrew ♂" },
          { "id": "027-a-f", "name": "Sandshrew ♀" },
          { "id": "028-a-m", "name": "Sandslash ♂" },
          { "id": "028-a-f", "name": "Sandslash ♀" },
          { "id": "037-a-m", "name": "Vulpix ♂" },
          { "id": "037-a-f", "name": "Vulpix ♀" },
          { "id": "038-a-m", "name": "Ninetales ♂" },
          { "id": "038-a-f", "name": "Ninetales ♀" },
          { "id": "050-a-m", "name": "Diglett ♂" },
          { "id": "050-a-f", "name": "Diglett ♀" },
          { "id": "051-a-m", "name": "Dugtrio ♂" },
          { "id": "051-a-f", "name": "Dugtrio ♀" },
          { "id": "052-a-m", "name": "Meowth ♂" },
          { "id": "052-a-f", "name": "Meowth ♀" },
          { "id": "053-a-m", "name": "Persian ♂" },
          { "id": "053-a-f", "name": "Persian ♀" },
          { "id": "074-a-m", "name": "Geodude ♂" },
          { "id": "074-a-f", "name": "Geodude ♀" },
          { "id": "075-a-m", "name": "Graveler ♂" },
          { "id": "075-a-f", "name": "Graveler ♀" },
          { "id": "076-a-m", "name": "Golem ♂" },
          { "id": "076-a-f", "name": "Golem ♀" },
          { "id": "088-a-m", "name": "Grimer ♂" },
          { "id": "088-a-f", "name": "Grimer ♀" },
          { "id": "089-a-m", "name": "Muk ♂" },
          { "id": "089-a-f", "name": "Muk ♀" },
          { "id": "103-a-m", "name": "Exeggutor ♂" },
          { "id": "103-a-f", "name": "Exeggutor ♀" },
          { "id": "105-a-m", "name": "Marowak ♂" },
          { "id": "105-a-f", "name": "Marowak ♀" }];
        this.genderSpinda = [{ "id": "327-m", "name": "#1 ♂" },
          { "id": "327-f", "name": "#1 ♀" },
          { "id": "327-3-m", "name": "#3 ♂" },
          { "id": "327-3-f", "name": "#3 ♀" },
          { "id": "327-6-m", "name": "#6 ♂" },
          { "id": "327-6-f", "name": "#6 ♀" },
          { "id": "327-7-m", "name": "#7 ♂" },
          { "id": "327-7-f", "name": "#7 ♀" },
          { "id": "327-8-m", "name": "#8 ♂" },
          { "id": "327-8-f", "name": "#8 ♀" }];
        this.genderGen1 = [{ "id": "001-m", "name": "Bulbasaur ♂" },
          { "id": "001-f", "name": "Bulbasaur ♀" },
          { "id": "002-m", "name": "Ivysaur ♂" },
          { "id": "002-f", "name": "Ivysaur ♀" },
          { "id": "003-m", "name": "Venusaur ♂" },
          { "id": "003-f", "name": "Venusaur ♀" },
          { "id": "004-m", "name": "Charmander ♂" },
          { "id": "004-f", "name": "Charmander ♀" },
          { "id": "005-m", "name": "Charmeleon ♂" },
          { "id": "005-f", "name": "Charmeleon ♀" },
          { "id": "006-m", "name": "Charizard ♂" },
          { "id": "006-f", "name": "Charizard ♀" },
          { "id": "007-m", "name": "Squirtle ♂" },
          { "id": "007-f", "name": "Squirtle ♀" },
          { "id": "008-m", "name": "Wortortle ♂" },
          { "id": "008-f", "name": "Wortortle ♀" },
          { "id": "009-m", "name": "Blastoise ♂" },
          { "id": "009-f", "name": "Blastoise ♀" },
          { "id": "010-m", "name": "Caterpie ♂" },
          { "id": "010-f", "name": "Caterpie ♀" },
          { "id": "011-m", "name": "Metapod ♂" },
          { "id": "011-f", "name": "Metapod ♀" },
          { "id": "012-m", "name": "Butterfree ♂" },
          { "id": "012-f", "name": "Butterfree ♀" },
          { "id": "013-m", "name": "Weedle ♂" },
          { "id": "013-f", "name": "Weedle ♀" },
          { "id": "014-m", "name": "Kakuna ♂" },
          { "id": "014-f", "name": "Kakuna ♀" },
          { "id": "015-m", "name": "Beedrill ♂" },
          { "id": "015-f", "name": "Beedrill ♀" },
          { "id": "016-m", "name": "Pidgey ♂" },
          { "id": "016-f", "name": "Pidgey ♀" },
          { "id": "017-m", "name": "Pidgeotto ♂" },
          { "id": "017-f", "name": "Pidgeotto ♀" },
          { "id": "018-m", "name": "Pidgeot ♂" },
          { "id": "018-f", "name": "Pidgeot ♀" },
          { "id": "019-m", "name": "Rattata ♂" },
          { "id": "019-f", "name": "Rattata ♀" },
          { "id": "020-m", "name": "Raticate ♂" },
          { "id": "020-f", "name": "Raticate ♀" },
          { "id": "021-m", "name": "Spearow ♂" },
          { "id": "021-f", "name": "Spearow ♀" },
          { "id": "022-m", "name": "Fearow ♂" },
          { "id": "022-f", "name": "Fearow ♀" },
          { "id": "023-m", "name": "Ekans ♂" },
          { "id": "023-f", "name": "Ekans ♀" },
          { "id": "024-m", "name": "Arbok ♂" },
          { "id": "024-f", "name": "Arbok ♀" },
          { "id": "025-m", "name": "Pikachu ♂" },
          { "id": "025-f", "name": "Pikachu ♀" },
          { "id": "026-m", "name": "Raichu ♂" },
          { "id": "026-f", "name": "Raichu ♀" },
          { "id": "027-m", "name": "Sandshrew ♂" },
          { "id": "027-f", "name": "Sandshrew ♀" },
          { "id": "028-m", "name": "Sandslash ♂" },
          { "id": "028-f", "name": "Sandslash ♀" },
          { "id": "029-f", "name": "Nidoran ♀" },
          { "id": "030-f", "name": "Nidorina ♀" },
          { "id": "031-f", "name": "Nidoqueen ♀" },
          { "id": "032-m", "name": "Nidoran ♂" },
          { "id": "033-m", "name": "Nidorino ♂" },
          { "id": "034-m", "name": "Nidoking ♂" },
          { "id": "035-m", "name": "Clefairy ♂" },
          { "id": "035-f", "name": "Clefairy ♀" },
          { "id": "036-m", "name": "Clefable ♂" },
          { "id": "036-f", "name": "Clefable ♀" },
          { "id": "037-m", "name": "Vulpix ♂" },
          { "id": "037-f", "name": "Vulpix ♀" },
          { "id": "038-m", "name": "Ninetales ♂" },
          { "id": "038-f", "name": "Ninetales ♀" },
          { "id": "039-m", "name": "Jigglypuff ♂" },
          { "id": "039-f", "name": "Jigglypuff ♀" },
          { "id": "040-m", "name": "Wigglytuff ♂" },
          { "id": "040-f", "name": "Wigglytuff ♀" },
          { "id": "041-m", "name": "Zubat ♂" },
          { "id": "041-f", "name": "Zubat ♀" },
          { "id": "042-m", "name": "Golbat ♂" },
          { "id": "042-f", "name": "Golbat ♀" },
          { "id": "043-m", "name": "Oddish ♂" },
          { "id": "043-f", "name": "Oddish ♀" },
          { "id": "044-m", "name": "Gloom ♂" },
          { "id": "044-f", "name": "Gloom ♀" },
          { "id": "045-m", "name": "Vileplume ♂" },
          { "id": "045-f", "name": "Vileplume ♀" },
          { "id": "046-m", "name": "Paras ♂" },
          { "id": "046-f", "name": "Paras ♀" },
          { "id": "047-m", "name": "Parasect ♂" },
          { "id": "047-f", "name": "Parasect ♀" },
          { "id": "048-m", "name": "Venonat ♂" },
          { "id": "048-f", "name": "Venonat ♀" },
          { "id": "049-m", "name": "Venomoth ♂" },
          { "id": "049-f", "name": "Venomoth ♀" },
          { "id": "050-m", "name": "Diglett ♂" },
          { "id": "050-f", "name": "Diglett ♀" },
          { "id": "051-m", "name": "Dugtrio ♂" },
          { "id": "051-f", "name": "Dugtrio ♀" },
          { "id": "052-m", "name": "Meowth ♂" },
          { "id": "052-f", "name": "Meowth ♀" },
          { "id": "053-m", "name": "Persian ♂" },
          { "id": "053-f", "name": "Persian ♀" },
          { "id": "054-m", "name": "Psyduck ♂" },
          { "id": "054-f", "name": "Psyduck ♀" },
          { "id": "055-m", "name": "Golduck ♂" },
          { "id": "055-f", "name": "Golduck ♀" },
          { "id": "056-m", "name": "Mankey ♂" },
          { "id": "056-f", "name": "Mankey ♀" },
          { "id": "057-m", "name": "Primeape ♂" },
          { "id": "057-f", "name": "Primeape ♀" },
          { "id": "058-m", "name": "Growlithe ♂" },
          { "id": "058-f", "name": "Growlithe ♀" },
          { "id": "059-m", "name": "Arcanine ♂" },
          { "id": "059-f", "name": "Arcanine ♀" },
          { "id": "060-m", "name": "Poliwag ♂" },
          { "id": "060-f", "name": "Poliwag ♀" },
          { "id": "061-m", "name": "Poliwhirl ♂" },
          { "id": "061-f", "name": "Poliwhirl ♀" },
          { "id": "062-m", "name": "Poliwrath ♂" },
          { "id": "062-f", "name": "Poliwrath ♀" },
          { "id": "063-m", "name": "Abra ♂" },
          { "id": "063-f", "name": "Abra ♀" },
          { "id": "064-m", "name": "Kadabra ♂" },
          { "id": "064-f", "name": "Kadabra ♀" },
          { "id": "065-m", "name": "Alakazam ♂" },
          { "id": "065-f", "name": "Alakazam ♀" },
          { "id": "066-m", "name": "Machop ♂" },
          { "id": "066-f", "name": "Machop ♀" },
          { "id": "067-m", "name": "Machoke ♂" },
          { "id": "067-f", "name": "Machoke ♀" },
          { "id": "068-m", "name": "Machamp ♂" },
          { "id": "068-f", "name": "Machamp ♀" },
          { "id": "069-m", "name": "Bellsprout ♂" },
          { "id": "069-f", "name": "Bellsprout ♀" },
          { "id": "070-m", "name": "Weepinbell ♂" },
          { "id": "070-f", "name": "Weepinbell ♀" },
          { "id": "071-m", "name": "Victreebel ♂" },
          { "id": "071-f", "name": "Victreebel ♀" },
          { "id": "072-m", "name": "Tentacool ♂" },
          { "id": "072-f", "name": "Tentacool ♀" },
          { "id": "073-m", "name": "Tentacruel ♂" },
          { "id": "073-f", "name": "Tentacruel ♀" },
          { "id": "074-m", "name": "Geodude ♂" },
          { "id": "074-f", "name": "Geodude ♀" },
          { "id": "075-m", "name": "Graveler ♂" },
          { "id": "075-f", "name": "Graveler ♀" },
          { "id": "076-m", "name": "Golem ♂" },
          { "id": "076-f", "name": "Golem ♀" },
          { "id": "077-m", "name": "Ponyta ♂" },
          { "id": "077-f", "name": "Ponyta ♀" },
          { "id": "078-m", "name": "Rapidash ♂" },
          { "id": "078-f", "name": "Rapidash ♀" },
          { "id": "079-m", "name": "Slowpoke ♂" },
          { "id": "079-f", "name": "Slowpoke ♀" },
          { "id": "080-m", "name": "Slowbro ♂" },
          { "id": "080-f", "name": "Slowbro ♀" },
          { "id": "083-m", "name": "Farfetch'd ♂" },
          { "id": "083-f", "name": "Farfetch'd ♀" },
          { "id": "084-m", "name": "Doduo ♂" },
          { "id": "084-f", "name": "Doduo ♀" },
          { "id": "085-m", "name": "Dodrio ♂" },
          { "id": "085-f", "name": "Dodrio ♀" },
          { "id": "086-m", "name": "Seel ♂" },
          { "id": "086-f", "name": "Seel ♀" },
          { "id": "087-m", "name": "Dewgong ♂" },
          { "id": "087-f", "name": "Dewgong ♀" },
          { "id": "088-m", "name": "Grimer ♂" },
          { "id": "088-f", "name": "Grimer ♀" },
          { "id": "089-m", "name": "Muk ♂" },
          { "id": "089-f", "name": "Muk ♀" },
          { "id": "090-m", "name": "Shellder ♂" },
          { "id": "090-f", "name": "Shellder ♀" },
          { "id": "091-m", "name": "Cloyster ♂" },
          { "id": "091-f", "name": "Cloyster ♀" },
          { "id": "092-m", "name": "Gastly ♂" },
          { "id": "092-f", "name": "Gastly ♀" },
          { "id": "093-m", "name": "Haunter ♂" },
          { "id": "093-f", "name": "Haunter ♀" },
          { "id": "094-m", "name": "Gengar ♂" },
          { "id": "094-f", "name": "Gengar ♀" },
          { "id": "095-m", "name": "Onix ♂" },
          { "id": "095-f", "name": "Onix ♀" },
          { "id": "096-m", "name": "Drowzee ♂" },
          { "id": "096-f", "name": "Drowzee ♀" },
          { "id": "097-m", "name": "Hypno ♂" },
          { "id": "097-f", "name": "Hypno ♀" },
          { "id": "098-m", "name": "Krabby ♂" },
          { "id": "098-f", "name": "Krabby ♀" },
          { "id": "099-m", "name": "Kingler ♂" },
          { "id": "099-f", "name": "Kingler ♀" },
          { "id": "102-m", "name": "Exeggcute ♂" },
          { "id": "102-f", "name": "Exeggcute ♀" },
          { "id": "103-m", "name": "Exeggutor ♂" },
          { "id": "103-f", "name": "Exeggutor ♀" },
          { "id": "104-m", "name": "Cubone ♂" },
          { "id": "104-f", "name": "Cubone ♀" },
          { "id": "105-m", "name": "Marowak ♂" },
          { "id": "105-f", "name": "Marowak ♀" },
          { "id": "106-m", "name": "Hitmonlee ♂" },
          { "id": "107-m", "name": "Hitmonchan ♂" },
          { "id": "108-m", "name": "Lickitung ♂" },
          { "id": "108-f", "name": "Lickitung ♀" },
          { "id": "109-m", "name": "Koffing ♂" },
          { "id": "109-f", "name": "Koffing ♀" },
          { "id": "110-m", "name": "Weezing ♂" },
          { "id": "110-f", "name": "Weezing ♀" },
          { "id": "111-m", "name": "Rhyhorn ♂" },
          { "id": "111-f", "name": "Rhyhorn ♀" },
          { "id": "112-m", "name": "Rhydon ♂" },
          { "id": "112-f", "name": "Rhydon ♀" },
          { "id": "113-f", "name": "Chansey ♀" },
          { "id": "114-m", "name": "Tangela ♂" },
          { "id": "114-f", "name": "Tangela ♀" },
          { "id": "115-f", "name": "Kangaskhan ♀" },
          { "id": "116-m", "name": "Horsea ♂" },
          { "id": "116-f", "name": "Horsea ♀" },
          { "id": "117-m", "name": "Seadra ♂" },
          { "id": "117-f", "name": "Seadra ♀" },
          { "id": "118-m", "name": "Goldeen ♂" },
          { "id": "118-f", "name": "Goldeen ♀" },
          { "id": "119-m", "name": "Seaking ♂" },
          { "id": "119-f", "name": "Seaking ♀" },
          { "id": "122-m", "name": "Mr. Mime ♂" },
          { "id": "122-f", "name": "Mr. Mime ♀" },
          { "id": "123-m", "name": "Scyther ♂" },
          { "id": "123-f", "name": "Scyther ♀" },
          { "id": "124-f", "name": "Jynx ♀" },
          { "id": "125-m", "name": "Electabuzz ♂" },
          { "id": "125-f", "name": "Electabuzz ♀" },
          { "id": "126-m", "name": "Magmar ♂" },
          { "id": "126-f", "name": "Magmar ♀" },
          { "id": "127-m", "name": "Pinsir ♂" },
          { "id": "127-f", "name": "Pinsir ♀" },
          { "id": "128-m", "name": "Tauros ♂" },
          { "id": "129-m", "name": "Magikarp ♂" },
          { "id": "129-f", "name": "Magikarp ♀" },
          { "id": "130-m", "name": "Gyarados ♂" },
          { "id": "130-f", "name": "Gyarados ♀" },
          { "id": "131-m", "name": "Lapras ♂" },
          { "id": "131-f", "name": "Lapras ♀" },
          { "id": "133-m", "name": "Eevee ♂" },
          { "id": "133-f", "name": "Eevee ♀" },
          { "id": "134-m", "name": "Vaporeon ♂" },
          { "id": "134-f", "name": "Vaporeon ♀" },
          { "id": "135-m", "name": "Jolteon ♂" },
          { "id": "135-f", "name": "Jolteon ♀" },
          { "id": "136-m", "name": "Flareon ♂" },
          { "id": "136-f", "name": "Flareon ♀" },
          { "id": "138-m", "name": "Omanyte ♂" },
          { "id": "138-f", "name": "Omanyte ♀" },
          { "id": "139-m", "name": "Omastar ♂" },
          { "id": "139-f", "name": "Omastar ♀" },
          { "id": "140-m", "name": "Kabuto ♂" },
          { "id": "140-f", "name": "Kabuto ♀" },
          { "id": "141-m", "name": "Kabutops ♂" },
          { "id": "141-f", "name": "Kabutops ♀" },
          { "id": "142-m", "name": "Aerodactyl ♂" },
          { "id": "142-f", "name": "Aerodactyl ♀" },
          { "id": "143-m", "name": "Snorlax ♂" },
          { "id": "143-f", "name": "Snorlax ♀" },
          { "id": "147-m", "name": "Dratini ♂" },
          { "id": "147-f", "name": "Dratini ♀" },
          { "id": "148-m", "name": "Dragonair ♂" },
          { "id": "148-f", "name": "Dragonair ♀" },
          { "id": "149-m", "name": "Dragonite ♂" },
          { "id": "149-f", "name": "Dragonite ♀" }];
        this.genderGen2 = [{ "id": "152-m", "name": "Chikorita ♂" },
          { "id": "153-m", "name": "Bayleef ♂" },
          { "id": "154-m", "name": "Meganium ♂" },
          { "id": "155-m", "name": "Cyndaquil ♂" },
          { "id": "156-m", "name": "Quilava ♂" },
          { "id": "157-m", "name": "Typhlosion ♂" },
          { "id": "158-m", "name": "Totodile ♂" },
          { "id": "159-m", "name": "Croconaw ♂" },
          { "id": "160-m", "name": "Feraligatr ♂" },
          { "id": "161-m", "name": "Sentret ♂" },
          { "id": "162-m", "name": "Furret ♂" },
          { "id": "163-m", "name": "Hoothoot ♂" },
          { "id": "164-m", "name": "Noctowl ♂" },
          { "id": "165-m", "name": "Ledyba ♂" },
          { "id": "166-m", "name": "Ledian ♂" },
          { "id": "167-m", "name": "Spinarak ♂" },
          { "id": "168-m", "name": "Ariados ♂" },
          { "id": "169-m", "name": "Crobat ♂" },
          { "id": "170-m", "name": "Chinchou ♂" },
          { "id": "171-m", "name": "Lanturn ♂" },
          { "id": "172-m", "name": "Pichu ♂" },
          { "id": "173-m", "name": "Cleffa ♂" },
          { "id": "174-m", "name": "Igglybuff ♂" },
          { "id": "175-m", "name": "Togepi ♂" },
          { "id": "176-m", "name": "Togetic ♂" },
          { "id": "177-m", "name": "Natu ♂" },
          { "id": "178-m", "name": "Xatu ♂" },
          { "id": "179-m", "name": "Mareep ♂" },
          { "id": "180-m", "name": "Flaaffy ♂" },
          { "id": "181-m", "name": "Ampharos ♂" },
          { "id": "182-m", "name": "Bellossom ♂" },
          { "id": "183-m", "name": "Marill ♂" },
          { "id": "184-m", "name": "Azumarill ♂" },
          { "id": "185-m", "name": "Sudowoodo ♂" },
          { "id": "186-m", "name": "Politoed ♂" },
          { "id": "187-m", "name": "Hoppip ♂" },
          { "id": "188-m", "name": "Skiploom ♂" },
          { "id": "189-m", "name": "Jumpluff ♂" },
          { "id": "190-m", "name": "Aipom ♂" },
          { "id": "191-m", "name": "Sunkern ♂" },
          { "id": "192-m", "name": "Sunflora ♂" },
          { "id": "193-m", "name": "Yanma ♂" },
          { "id": "194-m", "name": "Wooper ♂" },
          { "id": "195-m", "name": "Quagsire ♂" },
          { "id": "196-m", "name": "Espeon ♂" },
          { "id": "197-m", "name": "Umbreon ♂" },
          { "id": "198-m", "name": "Murkrow ♂" },
          { "id": "199-m", "name": "Slowking ♂" },
          { "id": "200-m", "name": "Misdreavus ♂" },
          { "id": "202-m", "name": "Wobbuffet ♂" },
          { "id": "203-m", "name": "Girafarig ♂" },
          { "id": "204-m", "name": "Pineco ♂" },
          { "id": "205-m", "name": "Forretress ♂" },
          { "id": "206-m", "name": "Dunsparce ♂" },
          { "id": "207-m", "name": "Gligar ♂" },
          { "id": "208-m", "name": "Steelix ♂" },
          { "id": "209-m", "name": "Snubbull ♂" },
          { "id": "210-m", "name": "Granbull ♂" },
          { "id": "211-m", "name": "Qwilfish ♂" },
          { "id": "212-m", "name": "Scizor ♂" },
          { "id": "213-m", "name": "Shuckle ♂" },
          { "id": "214-m", "name": "Heracross ♂" },
          { "id": "215-m", "name": "Sneasel ♂" },
          { "id": "216-m", "name": "Teddiursa ♂" },
          { "id": "217-m", "name": "Ursaring ♂" },
          { "id": "218-m", "name": "Slugma ♂" },
          { "id": "219-m", "name": "Magcargo ♂" },
          { "id": "220-m", "name": "Swinub ♂" },
          { "id": "221-m", "name": "Piloswine ♂" },
          { "id": "222-m", "name": "Corsola ♂" },
          { "id": "223-m", "name": "Remoraid ♂" },
          { "id": "224-m", "name": "Octillery ♂" },
          { "id": "225-m", "name": "Delibird ♂" },
          { "id": "226-m", "name": "Mantine ♂" },
          { "id": "227-m", "name": "Skarmory ♂" },
          { "id": "228-m", "name": "Houndour ♂" },
          { "id": "229-m", "name": "Houndoom ♂" },
          { "id": "230-m", "name": "Kingdra ♂" },
          { "id": "231-m", "name": "Phanpy ♂" },
          { "id": "232-m", "name": "Donphan ♂" },
          { "id": "234-m", "name": "Stantler ♂" },
          { "id": "236-m", "name": "Tyrogue ♂" },
          { "id": "237-m", "name": "Hitmontop ♂" },
          { "id": "238-f", "name": "Smoochum ♀" },
          { "id": "239-m", "name": "Elekid ♂" },
          { "id": "240-m", "name": "Magby ♂" },
          { "id": "241-f", "name": "Miltank ♀" },
          { "id": "242-f", "name": "Blissey ♀" },
          { "id": "246-m", "name": "Larvitar ♂" },
          { "id": "247-m", "name": "Pupitar ♂" },
          { "id": "248-m", "name": "Tyranitar ♂" },
          { "id": "152-f", "name": "Chikorita ♀" },
          { "id": "153-f", "name": "Bayleef ♀" },
          { "id": "154-f", "name": "Meganium ♀" },
          { "id": "155-f", "name": "Cyndaquil ♀" },
          { "id": "156-f", "name": "Quilava ♀" },
          { "id": "157-f", "name": "Typhlosion ♀" },
          { "id": "158-f", "name": "Totodile ♀" },
          { "id": "159-f", "name": "Croconaw ♀" },
          { "id": "160-f", "name": "Feraligatr ♀" },
          { "id": "161-f", "name": "Sentret ♀" },
          { "id": "162-f", "name": "Furret ♀" },
          { "id": "163-f", "name": "Hoothoot ♀" },
          { "id": "164-f", "name": "Noctowl ♀" },
          { "id": "165-f", "name": "Ledyba ♀" },
          { "id": "166-f", "name": "Ledian ♀" },
          { "id": "167-f", "name": "Spinarak ♀" },
          { "id": "168-f", "name": "Ariados ♀" },
          { "id": "169-f", "name": "Crobat ♀" },
          { "id": "170-f", "name": "Chinchou ♀" },
          { "id": "171-f", "name": "Lanturn ♀" },
          { "id": "172-f", "name": "Pichu ♀" },
          { "id": "173-f", "name": "Cleffa ♀" },
          { "id": "174-f", "name": "Igglybuff ♀" },
          { "id": "175-f", "name": "Togepi ♀" },
          { "id": "176-f", "name": "Togetic ♀" },
          { "id": "177-f", "name": "Natu ♀" },
          { "id": "178-f", "name": "Xatu ♀" },
          { "id": "179-f", "name": "Mareep ♀" },
          { "id": "180-f", "name": "Flaaffy ♀" },
          { "id": "181-f", "name": "Ampharos ♀" },
          { "id": "182-f", "name": "Bellossom ♀" },
          { "id": "183-f", "name": "Marill ♀" },
          { "id": "184-f", "name": "Azumarill ♀" },
          { "id": "185-f", "name": "Sudowoodo ♀" },
          { "id": "186-f", "name": "Politoed ♀" },
          { "id": "187-f", "name": "Hoppip ♀" },
          { "id": "188-f", "name": "Skiploom ♀" },
          { "id": "189-f", "name": "Jumpluff ♀" },
          { "id": "190-f", "name": "Aipom ♀" },
          { "id": "191-f", "name": "Sunkern ♀" },
          { "id": "192-f", "name": "Sunflora ♀" },
          { "id": "193-f", "name": "Yanma ♀" },
          { "id": "194-f", "name": "Wooper ♀" },
          { "id": "195-f", "name": "Quagsire ♀" },
          { "id": "196-f", "name": "Espeon ♀" },
          { "id": "197-f", "name": "Umbreon ♀" },
          { "id": "198-f", "name": "Murkrow ♀" },
          { "id": "199-f", "name": "Slowking ♀" },
          { "id": "200-f", "name": "Misdreavus ♀" },
          { "id": "202-f", "name": "Wobbuffet ♀" },
          { "id": "203-f", "name": "Girafarig ♀" },
          { "id": "204-f", "name": "Pineco ♀" },
          { "id": "205-f", "name": "Forretress ♀" },
          { "id": "206-f", "name": "Dunsparce ♀" },
          { "id": "207-f", "name": "Gligar ♀" },
          { "id": "208-f", "name": "Steelix ♀" },
          { "id": "209-f", "name": "Snubbull ♀" },
          { "id": "210-f", "name": "Granbull ♀" },
          { "id": "211-f", "name": "Qwilfish ♀" },
          { "id": "212-f", "name": "Scizor ♀" },
          { "id": "213-f", "name": "Shuckle ♀" },
          { "id": "214-f", "name": "Heracross ♀" },
          { "id": "215-f", "name": "Sneasel ♀" },
          { "id": "216-f", "name": "Teddiursa ♀" },
          { "id": "217-f", "name": "Ursaring ♀" },
          { "id": "218-f", "name": "Slugma ♀" },
          { "id": "219-f", "name": "Magcargo ♀" },
          { "id": "220-f", "name": "Swinub ♀" },
          { "id": "221-f", "name": "Piloswine ♀" },
          { "id": "222-f", "name": "Corsola ♀" },
          { "id": "223-f", "name": "Remoraid ♀" },
          { "id": "224-f", "name": "Octillery ♀" },
          { "id": "225-f", "name": "Delibird ♀" },
          { "id": "226-f", "name": "Mantine ♀" },
          { "id": "227-f", "name": "Skarmory ♀" },
          { "id": "228-f", "name": "Houndour ♀" },
          { "id": "229-f", "name": "Houndoom ♀" },
          { "id": "230-f", "name": "Kingdra ♀" },
          { "id": "231-f", "name": "Phanpy ♀" },
          { "id": "232-f", "name": "Donphan ♀" },
          { "id": "234-f", "name": "Stantler ♀" },
          { "id": "239-f", "name": "Elekid ♀" },
          { "id": "240-f", "name": "Magby ♀" },
          { "id": "246-f", "name": "Larvitar ♀" },
          { "id": "247-f", "name": "Pupitar ♀" },
          { "id": "248-f", "name": "Tyranitar ♀" }];
        this.genderGen3 = [{ "id": "252-m", "name": "Treecko ♂" },
          { "id": "253-m", "name": "Grovyle ♂" },
          { "id": "254-m", "name": "Sceptile ♂" },
          { "id": "255-m", "name": "Torchic ♂" },
          { "id": "256-m", "name": "Combusken ♂" },
          { "id": "257-m", "name": "Blaziken ♂" },
          { "id": "258-m", "name": "Mudkip ♂" },
          { "id": "259-m", "name": "Marshtomp ♂" },
          { "id": "260-m", "name": "Swampert ♂" },
          { "id": "261-m", "name": "Poochyena ♂" },
          { "id": "262-m", "name": "Mightyena ♂" },
          { "id": "263-m", "name": "Zigzagoon ♂" },
          { "id": "264-m", "name": "Linoone ♂" },
          { "id": "265-m", "name": "Wurmple ♂" },
          { "id": "266-m", "name": "Silcoon ♂" },
          { "id": "267-m", "name": "Beautifly ♂" },
          { "id": "268-m", "name": "Cascoon ♂" },
          { "id": "269-m", "name": "Dustox ♂" },
          { "id": "270-m", "name": "Lotad ♂" },
          { "id": "271-m", "name": "Lombre ♂" },
          { "id": "272-m", "name": "Ludicolo ♂" },
          { "id": "273-m", "name": "Seedot ♂" },
          { "id": "274-m", "name": "Nuzleaf ♂" },
          { "id": "275-m", "name": "Shiftry ♂" },
          { "id": "276-m", "name": "Taillow ♂" },
          { "id": "277-m", "name": "Swellow ♂" },
          { "id": "278-m", "name": "Wingull ♂" },
          { "id": "279-m", "name": "Pelipper ♂" },
          { "id": "280-m", "name": "Ralts ♂" },
          { "id": "281-m", "name": "Kirlia ♂" },
          { "id": "282-m", "name": "Gardevoir ♂" },
          { "id": "283-m", "name": "Surskit ♂" },
          { "id": "284-m", "name": "Masquerain ♂" },
          { "id": "285-m", "name": "Shroomish ♂" },
          { "id": "286-m", "name": "Breloom ♂" },
          { "id": "287-m", "name": "Slakoth ♂" },
          { "id": "288-m", "name": "Vigoroth ♂" },
          { "id": "289-m", "name": "Slaking ♂" },
          { "id": "290-m", "name": "Nincada ♂" },
          { "id": "291-m", "name": "Ninjask ♂" },
          { "id": "293-m", "name": "Whismur ♂" },
          { "id": "294-m", "name": "Loudred ♂" },
          { "id": "295-m", "name": "Exploud ♂" },
          { "id": "296-m", "name": "Makuhita ♂" },
          { "id": "297-m", "name": "Hariyama ♂" },
          { "id": "298-m", "name": "Azurill ♂" },
          { "id": "299-m", "name": "Nosepass ♂" },
          { "id": "300-m", "name": "Skitty ♂" },
          { "id": "301-m", "name": "Delcatty ♂" },
          { "id": "302-m", "name": "Sableye ♂" },
          { "id": "303-m", "name": "Mawile ♂" },
          { "id": "304-m", "name": "Aron ♂" },
          { "id": "305-m", "name": "Lairon ♂" },
          { "id": "306-m", "name": "Aggron ♂" },
          { "id": "307-m", "name": "Meditite ♂" },
          { "id": "308-m", "name": "Medicham ♂" },
          { "id": "309-m", "name": "Electrike ♂" },
          { "id": "310-m", "name": "Manectric ♂" },
          { "id": "311-m", "name": "Plusle ♂" },
          { "id": "312-m", "name": "Minun ♂" },
          { "id": "313-m", "name": "Volbeat ♂" },
          { "id": "314-f", "name": "Illumise ♀" },
          { "id": "315-m", "name": "Roselia ♂" },
          { "id": "316-m", "name": "Gulpin ♂" },
          { "id": "317-m", "name": "Swalot ♂" },
          { "id": "318-m", "name": "Carvanha ♂" },
          { "id": "319-m", "name": "Sharpedo ♂" },
          { "id": "320-m", "name": "Wailmer ♂" },
          { "id": "321-m", "name": "Wailord ♂" },
          { "id": "322-m", "name": "Numel ♂" },
          { "id": "323-m", "name": "Camerupt ♂" },
          { "id": "324-m", "name": "Torkoal ♂" },
          { "id": "325-m", "name": "Spoink ♂" },
          { "id": "326-m", "name": "Grumpig ♂" },
          { "id": "327-m", "name": "Spinda ♂" },
          { "id": "328-m", "name": "Trapinch ♂" },
          { "id": "329-m", "name": "Vibrava ♂" },
          { "id": "330-m", "name": "Flygon ♂" },
          { "id": "331-m", "name": "Cacnea ♂" },
          { "id": "332-m", "name": "Cacturne ♂" },
          { "id": "333-m", "name": "Swablu ♂" },
          { "id": "334-m", "name": "Altaria ♂" },
          { "id": "335-m", "name": "Zangoose ♂" },
          { "id": "336-m", "name": "Seviper ♂" },
          { "id": "339-m", "name": "Barboach ♂" },
          { "id": "340-m", "name": "Whiscash ♂" },
          { "id": "341-m", "name": "Corphish ♂" },
          { "id": "342-m", "name": "Crawdaunt ♂" },
          { "id": "345-m", "name": "Lileep ♂" },
          { "id": "346-m", "name": "Cradily ♂" },
          { "id": "347-m", "name": "Anorith ♂" },
          { "id": "348-m", "name": "Armaldo ♂" },
          { "id": "349-m", "name": "Feebas ♂" },
          { "id": "350-m", "name": "Milotic ♂" },
          { "id": "351-m", "name": "Castform ♂" },
          { "id": "353-m", "name": "Shuppet ♂" },
          { "id": "354-m", "name": "Banette ♂" },
          { "id": "355-m", "name": "Duskull ♂" },
          { "id": "356-m", "name": "Dusclops ♂" },
          { "id": "357-m", "name": "Tropius ♂" },
          { "id": "358-m", "name": "Chimecho ♂" },
          { "id": "359-m", "name": "Absol ♂" },
          { "id": "360-m", "name": "Wynaut ♂" },
          { "id": "361-m", "name": "Snorunt ♂" },
          { "id": "362-m", "name": "Glalie ♂" },
          { "id": "363-m", "name": "Spheal ♂" },
          { "id": "364-m", "name": "Sealeo ♂" },
          { "id": "365-m", "name": "Walrein ♂" },
          { "id": "369-m", "name": "Relicanth ♂" },
          { "id": "370-m", "name": "Luvdisc ♂" },
          { "id": "371-m", "name": "Bagon ♂" },
          { "id": "372-m", "name": "Shelgon ♂" },
          { "id": "373-m", "name": "Salamence ♂" },
          { "id": "380-f", "name": "Latias ♀" },
          { "id": "381-m", "name": "Latios ♂" },
          { "id": "252-f", "name": "Treecko ♀" },
          { "id": "253-f", "name": "Grovyle ♀" },
          { "id": "254-f", "name": "Sceptile ♀" },
          { "id": "255-f", "name": "Torchic ♀" },
          { "id": "256-f", "name": "Combusken ♀" },
          { "id": "257-f", "name": "Blaziken ♀" },
          { "id": "258-f", "name": "Mudkip ♀" },
          { "id": "259-f", "name": "Marshtomp ♀" },
          { "id": "260-f", "name": "Swampert ♀" },
          { "id": "261-f", "name": "Poochyena ♀" },
          { "id": "262-f", "name": "Mightyena ♀" },
          { "id": "263-f", "name": "Zigzagoon ♀" },
          { "id": "264-f", "name": "Linoone ♀" },
          { "id": "265-f", "name": "Wurmple ♀" },
          { "id": "266-f", "name": "Silcoon ♀" },
          { "id": "267-f", "name": "Beautifly ♀" },
          { "id": "268-f", "name": "Cascoon ♀" },
          { "id": "269-f", "name": "Dustox ♀" },
          { "id": "270-f", "name": "Lotad ♀" },
          { "id": "271-f", "name": "Lombre ♀" },
          { "id": "272-f", "name": "Ludicolo ♀" },
          { "id": "273-f", "name": "Seedot ♀" },
          { "id": "274-f", "name": "Nuzleaf ♀" },
          { "id": "275-f", "name": "Shiftry ♀" },
          { "id": "276-f", "name": "Taillow ♀" },
          { "id": "277-f", "name": "Swellow ♀" },
          { "id": "278-f", "name": "Wingull ♀" },
          { "id": "279-f", "name": "Pelipper ♀" },
          { "id": "280-f", "name": "Ralts ♀" },
          { "id": "281-f", "name": "Kirlia ♀" },
          { "id": "282-f", "name": "Gardevoir ♀" },
          { "id": "283-f", "name": "Surskit ♀" },
          { "id": "284-f", "name": "Masquerain ♀" },
          { "id": "285-f", "name": "Shroomish ♀" },
          { "id": "286-f", "name": "Breloom ♀" },
          { "id": "287-f", "name": "Slakoth ♀" },
          { "id": "288-f", "name": "Vigoroth ♀" },
          { "id": "289-f", "name": "Slaking ♀" },
          { "id": "290-f", "name": "Nincada ♀" },
          { "id": "291-f", "name": "Ninjask ♀" },
          { "id": "293-f", "name": "Whismur ♀" },
          { "id": "294-f", "name": "Loudred ♀" },
          { "id": "295-f", "name": "Exploud ♀" },
          { "id": "296-f", "name": "Makuhita ♀" },
          { "id": "297-f", "name": "Hariyama ♀" },
          { "id": "298-f", "name": "Azurill ♀" },
          { "id": "299-f", "name": "Nosepass ♀" },
          { "id": "300-f", "name": "Skitty ♀" },
          { "id": "301-f", "name": "Delcatty ♀" },
          { "id": "302-f", "name": "Sableye ♀" },
          { "id": "303-f", "name": "Mawile ♀" },
          { "id": "304-f", "name": "Aron ♀" },
          { "id": "305-f", "name": "Lairon ♀" },
          { "id": "306-f", "name": "Aggron ♀" },
          { "id": "307-f", "name": "Meditite ♀" },
          { "id": "308-f", "name": "Medicham ♀" },
          { "id": "309-f", "name": "Electrike ♀" },
          { "id": "310-f", "name": "Manectric ♀" },
          { "id": "311-f", "name": "Plusle ♀" },
          { "id": "312-f", "name": "Minun ♀" },
          { "id": "315-f", "name": "Roselia ♀" },
          { "id": "316-f", "name": "Gulpin ♀" },
          { "id": "317-f", "name": "Swalot ♀" },
          { "id": "318-f", "name": "Carvanha ♀" },
          { "id": "319-f", "name": "Sharpedo ♀" },
          { "id": "320-f", "name": "Wailmer ♀" },
          { "id": "321-f", "name": "Wailord ♀" },
          { "id": "322-f", "name": "Numel ♀" },
          { "id": "323-f", "name": "Camerupt ♀" },
          { "id": "324-f", "name": "Torkoal ♀" },
          { "id": "325-f", "name": "Spoink ♀" },
          { "id": "326-f", "name": "Grumpig ♀" },
          { "id": "327-f", "name": "Spinda ♀" },
          { "id": "328-f", "name": "Trapinch ♀" },
          { "id": "329-f", "name": "Vibrava ♀" },
          { "id": "330-f", "name": "Flygon ♀" },
          { "id": "331-f", "name": "Cacnea ♀" },
          { "id": "332-f", "name": "Cacturne ♀" },
          { "id": "333-f", "name": "Swablu ♀" },
          { "id": "334-f", "name": "Altaria ♀" },
          { "id": "335-f", "name": "Zangoose ♀" },
          { "id": "336-f", "name": "Seviper ♀" },
          { "id": "339-f", "name": "Barboach ♀" },
          { "id": "340-f", "name": "Whiscash ♀" },
          { "id": "341-f", "name": "Corphish ♀" },
          { "id": "342-f", "name": "Crawdaunt ♀" },
          { "id": "345-f", "name": "Lileep ♀" },
          { "id": "346-f", "name": "Cradily ♀" },
          { "id": "347-f", "name": "Anorith ♀" },
          { "id": "348-f", "name": "Armaldo ♀" },
          { "id": "349-f", "name": "Feebas ♀" },
          { "id": "350-f", "name": "Milotic ♀" },
          { "id": "351-f", "name": "Castform ♀" },
          { "id": "353-f", "name": "Shuppet ♀" },
          { "id": "354-f", "name": "Banette ♀" },
          { "id": "355-f", "name": "Duskull ♀" },
          { "id": "356-f", "name": "Dusclops ♀" },
          { "id": "357-f", "name": "Tropius ♀" },
          { "id": "358-f", "name": "Chimecho ♀" },
          { "id": "359-f", "name": "Absol ♀" },
          { "id": "360-f", "name": "Wynaut ♀" },
          { "id": "361-f", "name": "Snorunt ♀" },
          { "id": "362-f", "name": "Glalie ♀" },
          { "id": "363-f", "name": "Spheal ♀" },
          { "id": "364-f", "name": "Sealeo ♀" },
          { "id": "365-f", "name": "Walrein ♀" },
          { "id": "369-f", "name": "Relicanth ♀" },
          { "id": "370-f", "name": "Luvdisc ♀" },
          { "id": "371-f", "name": "Bagon ♀" },
          { "id": "372-f", "name": "Shelgon ♀" },
          { "id": "373-f", "name": "Salamence ♀" }];
        /*this.genderGen4 = [{ "id": "387", "name": "Turtwig" },
          { "id": "388", "name": "Grotle" },
          { "id": "389", "name": "Torterra" },
          { "id": "390", "name": "Chimchar" },
          { "id": "391", "name": "Monferno" },
          { "id": "392", "name": "Infernape" },
          { "id": "393", "name": "Piplup" },
          { "id": "394", "name": "Prinplup" },
          { "id": "395", "name": "Empoleon" },
          { "id": "396", "name": "Starly" },
          { "id": "397", "name": "Staravia" },
          { "id": "398", "name": "Staraptor" },
          { "id": "399", "name": "Bidoof" },
          { "id": "400", "name": "Bibarel" },
          { "id": "401", "name": "Kricketot" },
          { "id": "402", "name": "Kricketune" },
          { "id": "403", "name": "Shinx" },
          { "id": "404", "name": "Luxio" },
          { "id": "405", "name": "Luxray" },
          { "id": "406", "name": "Budew" },
          { "id": "417", "name": "Pachirisu" },
          { "id": "418", "name": "Buizel" },
          { "id": "425", "name": "Drifloon" },
          { "id": "426", "name": "Drifblim" },
          { "id": "427", "name": "Buneary" },
          { "id": "428", "name": "Lopunny" },
          { "id": "434", "name": "Stunky" },
          { "id": "435", "name": "Skuntank" },
          { "id": "441", "name": "Chatot" },
          { "id": "442", "name": "Spiritomb" },
          { "id": "447", "name": "Riolu" },
          { "id": "448", "name": "Lucario" },
          { "id": "455", "name": "Carnivine" },
          { "id": "487", "name": "Giratina" }];*/
    }
    return PokedexService;
}());
angular
    .module('app', ['angular.filter'])
    .controller('PokedexController', PokedexController)
    .service('pokedexService', PokedexService);
